---
title: "Graficos_tesis"
author: "Carlos Pasquier Jaramillo"
date: "`r Sys.Date()`"
output: html_document
---

# Librerias

```{r}
library(readr)
library(tidyverse)
library(raster)
library(geodata)
library(sf)
library(gridExtra)
library(SpatialExtremes)
library(latex2exp)
library(gridExtra)
library(grid)
library(matrixStats)

```



```{r}
proceso_estimacion <- function(params_covariables, params_parametros, nsites, m, cov, dist_mat,modelo) {
  # Asignar los parámetros de covariables
  y_train_gamma_auxiliar <- params_covariables
  # Asignar los parámetros de los otros valores
  y_train_phi_auxiliar <- params_parametros[1]
  y_train_sigma_auxiliar <- params_parametros[2]
  
  
  
  
  if (modelo!='D2' | modelo!='D1'){
    y_train_beta3_auxiliar <- params_parametros[3]
    y_train_rho_auxiliar <- params_parametros[4]
    
    # Simular X3 usando la función simular_X3
    X3_auxiliar_completo <-
      simular_X3(m,
                 y_train_rho_auxiliar,
                 y_train_beta3_auxiliar,
                 nsites,
                 dist_mat)
    
    
  }
  
  
  # Inicialización de X_train_auxiliar usando el código anterior
  X_train_auxiliar <- matrix(0, ncol = nsites, nrow = m)
  
  
  if (modelo == 'DY') {
    X2_auxiliar <- simular_X1(m, y_train_phi_auxiliar)
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      # Simular X2 usando la función simular_logAR1
      X1_auxiliar <-
        simular_X1(m, y_train_sigma_auxiliar)
      
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <-
        X2_auxiliar * X3_auxiliar * covariables_auxiliar * X1_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  
  
  
  
  if (modelo == 'D8') {
    X1_auxiliar <- simular_X1(m, 0.5)
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      # Simular X2 usando la función simular_logAR1
      X2_auxiliar <-
        simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
      
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <-
        X2_auxiliar * X3_auxiliar * covariables_auxiliar * X1_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  
  
  if (modelo == 'D7') {
    X1_auxiliar <- simular_X1(m, 0.5)
    # Simular X2 usando la función simular_logAR1
    X2_auxiliar <-
      simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <-
        X2_auxiliar * X3_auxiliar * covariables_auxiliar * X1_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  
  if (modelo == 'D6') {
    # Simular X2 usando la función simular_logAR1
    X2_auxiliar <-
      simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      X1_auxiliar <- simular_X1(m, 0.5)
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <-
        X2_auxiliar * X3_auxiliar * covariables_auxiliar * X1_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  
  if (modelo == 'D5') {
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      X1_auxiliar <- simular_X1(m, 0.5)
      # Simular X2 usando la función simular_logAR1
      X2_auxiliar <-
        simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <-
        X2_auxiliar * X3_auxiliar * covariables_auxiliar * X1_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  if (modelo == 'D4') {
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      # Simular X2 usando la función simular_logAR1
      X2_auxiliar <-
        simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <- X2_auxiliar * X3_auxiliar * covariables_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  if (modelo == 'D3') {
    # Simular X2 usando la función simular_logAR1
    X2_auxiliar <-
      simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <- X2_auxiliar * X3_auxiliar * covariables_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  
  
  if (modelo == 'D2') {
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      # Simular X2 usando la función simular_logAR1
      X2_auxiliar <-
        simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <- X2_auxiliar * covariables_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  
  if (modelo == 'D1') {
    # Simular X2 usando la función simular_logAR1
    X2_auxiliar <-
      simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
    
    # Bucle para calcular las covariables y valores para cada sitio
    for (sitio in 1:nsites) {
      # Obtener el valor correspondiente de X3 para el sitio
      X3_auxiliar <- X3_auxiliar_completo[, sitio]
      
      # Calcular la covariable auxiliar
      covariables_auxiliar <-
        calculo_covariable(cov[sitio,], y_train_gamma_auxiliar)
      
      # Calcular los valores auxiliares
      auxi <- X2_auxiliar * covariables_auxiliar
      
      # Calcular el cuantil 75
      cuantil_75 <- quantile(auxi, 0.75)
      
      # Asignar el valor mínimo entre auxi y el cuantil 75
      X_train_auxiliar[, sitio] <-
        ifelse(auxi < cuantil_75, cuantil_75, auxi)
    }
    
    # Retornar la matriz final
    return(X_train_auxiliar)
  }
  
  
}




```

```{r}
simular_logAR1 <- function(n, phi, sigma) {
  observaciones <- numeric(n)
  ce <- -(sigma^2) / (2 * (1 - phi^2))
  observaciones[1] <- exp(rnorm(1, mean = ce, sd = sigma / sqrt(1 - phi^2)))
  
  for (t in 2:n) {
    observaciones[t] <- exp((1 - phi) * ce + phi * log(observaciones[t - 1]) + rnorm(1, mean = 0, sd = sigma))
  }
  
  return(observaciones)
}

simular_X1 <- function(n, beta1) {
  X1 <- (rexp(n, rate = 1) ^ beta1) / gamma(1 + beta1)
  return(X1)
}

simular_X3 <- function(n, rho, beta3, nsites, dist_mat) {
  # Crear la matriz de covarianzas Sigma
  Sigma <- exp(-dist_mat / rho)
  
  # Simulación de vectores gaussianos multivariados independientes
  Gauss <- MASS::mvrnorm(n, mu = rep(0, nsites), Sigma = Sigma)
  
  # Transformación según la distribución Gamma
  X3 <- qgamma(pnorm(Gauss), shape = beta3, scale = 1) / (beta3 - 1)
  
  return(1/X3)
}

calculo_covariable <- function(fila_locacion, gamma_cov) {
  suma <- 0
  for (z in 1:length(gamma_cov)) {
    suma <- suma + gamma_cov[z] * fila_locacion[z]
  }
  return(exp(suma))
}
```


```{r}
# max(simular_X3(1000,1.5,5,nsites_train_test,dist_mat_train_test)[,1])
# 
# quantile(simular_X3(1000,1.5,1.5,nsites_train_test,dist_mat_train_test)[,1],0.99)
# quantile(simular_X3(1000,1.5,1000,nsites_train_test,dist_mat_train_test)[,1],0.99)
```

```{r}
# quantile(simular_X3(1000,1.5,1.5,nsites_train_test,dist_mat_train_test)[,30],0.95)
# quantile(simular_X3(1000,1.5,5,nsites_train_test,dist_mat_train_test)[,30],0.95)
```
```{r}
# simular_logAR1(100,-0.9999,0.5)
```



# Traceplot



## Simulacion Pasquier


```{r}



estimacion_t_simulacion_D8_extremo_V1_c1 <-  read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_D8_extremo_V2_V12_c1.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 1)

estimacion_t_simulacion_D8_extremo_V1_c2 <-  read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_D8_extremo_V2_V12_c2.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 2)
  
estimacion_t_simulacion_D8_extremo_V1 <- rbind(estimacion_t_simulacion_D8_extremo_V1_c1,estimacion_t_simulacion_D8_extremo_V1_c2)



estimacion_t_simulacion_D8_extremo_V6_c1 <-  read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_D8_extremo_V6_V16_c1.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 1)

estimacion_t_simulacion_D8_extremo_V6_c2 <-  read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_D8_extremo_V6_V16_c2.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 2)
  
estimacion_t_simulacion_D8_extremo_V6 <- rbind(estimacion_t_simulacion_D8_extremo_V6_c1,estimacion_t_simulacion_D8_extremo_V6_c2)




```

```{r}
df_long <- estimacion_t_simulacion_D8_extremo_V1 %>%
  pivot_longer(cols = starts_with("posterior"), 
               names_to = "parametro", 
               values_to = "valor")

valores_reales <- data.frame(parametro=c("posterior_g1","posterior_g2","posterior_g3","posterior_g4","posterior_phi","posterior_sigma","posterior_beta3","posterior_rho"),real=c(exp(1),1,1,1,0.5,1 ,5,0.5))

df_long <- df_long %>% left_join(valores_reales,by='parametro')

# Definir el orden de los parámetros en las facetas
orden_parametros <- c("posterior_g1", "posterior_g2", "posterior_g3", "posterior_g4", 
                      "posterior_phi", "posterior_sigma", "posterior_beta3", "posterior_rho")
orden_parametros <- gsub("posterior_", "", orden_parametros)
# Asegurarnos que 'cadena' esté como factor para diferenciar las dos cadenas
df_long$cadenas <- factor(df_long$cadena, levels = c(1, 2), labels = c("Primera cadena", "Segunda cadena"))

# Aseguramos que los parámetros estén en el orden correcto y quitamos "posterior"
df_long$parametro <- factor(gsub("posterior_", "", df_long$parametro), levels = orden_parametros)

df_long$parametro <- factor(df_long$parametro,labels=c("g1" = parse(text=TeX("$\\gamma_0$")), 
                                      "g2" = parse(text=TeX("$\\gamma_1$")), 
                                      "g3" = parse(text=TeX("$\\gamma_2$")), 
                                      "g4" = parse(text=TeX("$\\gamma_3$")), 
                                      "phi" = parse(text=TeX("$\\phi$")), 
                                      "sigma" = parse(text=TeX("$\\sigma$")), 
                                      "beta3" = parse(text=TeX("$\\beta_3$")), 
                                      "rho" = parse(text=TeX("$\\rho$"))  ))


# Graficamos los traceplots
p1 <- ggplot(df_long, aes(x = iteracion, y = valor, color = cadenas)) +
  geom_line(linewidth=0.5, alpha=0.6) +geom_hline(aes(yintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_y", 
             labeller = label_parsed,ncol = 4) +
  scale_color_manual(values = c("Primera cadena" = "red", "Segunda cadena" = "#377eb8"))+
   # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
   #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
  scale_x_continuous(breaks = c(0,5000,10000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
p1
# Graficamos los traceplots
h1 <- ggplot(df_long, aes(x = valor, fill = cadenas)) +
  geom_histogram(position = "identity", bins = 25,alpha=0.6) +geom_vline(aes(xintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_x", 
             labeller = label_parsed,ncol = 4) +
  scale_fill_manual(values = c("Primera cadena" = "#e41a1c", "Segunda cadena" = "#377eb8"))+
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
h1
```

```{r}
df_long <- estimacion_t_simulacion_D8_extremo_V6 %>%
  pivot_longer(cols = starts_with("posterior"), 
               names_to = "parametro", 
               values_to = "valor")

valores_reales <- data.frame(parametro=c("posterior_g1","posterior_g2","posterior_g3","posterior_g4","posterior_phi","posterior_sigma","posterior_beta3","posterior_rho"),real=c(exp(1),1,1,1,0.5,1 ,5,0.5))

df_long <- df_long %>% left_join(valores_reales,by='parametro')

# Definir el orden de los parámetros en las facetas
orden_parametros <- c("posterior_g1", "posterior_g2", "posterior_g3", "posterior_g4", 
                      "posterior_phi", "posterior_sigma", "posterior_beta3", "posterior_rho")
orden_parametros <- gsub("posterior_", "", orden_parametros)
# Asegurarnos que 'cadena' esté como factor para diferenciar las dos cadenas
df_long$cadenas <- factor(df_long$cadena, levels = c(1, 2), labels = c("Primera cadena", "Segunda cadena"))

# Aseguramos que los parámetros estén en el orden correcto y quitamos "posterior"
df_long$parametro <- factor(gsub("posterior_", "", df_long$parametro), levels = orden_parametros)

df_long$parametro <- factor(df_long$parametro,labels=c("g1" = parse(text=TeX("$\\gamma_0$")), 
                                      "g2" = parse(text=TeX("$\\gamma_1$")), 
                                      "g3" = parse(text=TeX("$\\gamma_2$")), 
                                      "g4" = parse(text=TeX("$\\gamma_3$")), 
                                      "phi" = parse(text=TeX("$\\phi$")), 
                                      "sigma" = parse(text=TeX("$\\sigma$")), 
                                      "beta3" = parse(text=TeX("$\\beta_3$")), 
                                      "rho" = parse(text=TeX("$\\rho$"))  ))


# Graficamos los traceplots
p2 <- ggplot(df_long, aes(x = iteracion, y = valor, color = cadenas)) +
  geom_line(linewidth=0.5, alpha=0.6) +geom_hline(aes(yintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_y", 
             labeller = label_parsed,ncol = 4) +
  scale_color_manual(values = c("Primera cadena" = "red", "Segunda cadena" = "#377eb8"))+
   # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
   #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
  scale_x_continuous(breaks = c(0,5000,10000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
p2
# Graficamos los traceplots
h2 <- ggplot(df_long, aes(x = valor, fill = cadenas)) +
  geom_histogram(position = "identity", bins = 25,alpha=0.6) +geom_vline(aes(xintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_x", 
             labeller = label_parsed,ncol = 4) +
  scale_fill_manual(values = c("Primera cadena" = "#e41a1c", "Segunda cadena" = "#377eb8"))+
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
h2
```



```{r}



y.grob <- textGrob("Value", 
                   gp=gpar(), rot=90)

x.grob <- textGrob("Iteration", 
                   gp=gpar())

fig <- grid.arrange(p1,p2, left = y.grob, bottom = x.grob
)



ggsave("img_articulo/grafico_traceplot_simulacion_D8.pdf", plot = fig, width = 7.5, height = 5)


y.grob <- textGrob("Frequency", 
                   gp=gpar(), rot=90)

x.grob <- textGrob("Value", 
                   gp=gpar())


fig <- fig <- grid.arrange(h1,h2, left = y.grob, bottom = x.grob
)
ggsave("img_articulo/grafico_histograma_simulacion_D8.pdf", plot = fig, width = 7.5, height = 5)



```



## Simulacion YADAV

```{r}
archivos_simulacion <- list.files('Traceplot_simulacion_phi')
archivos_simulacion_YADAV <- c()
for (arc in archivos_simulacion) {
  if( grepl('DY', arc) && grepl('_t_', arc) && grepl('c1', arc)){
    archivos_simulacion_YADAV <- c(archivos_simulacion_YADAV,arc)
  }
}

archivos_simulacion_YADAV <- sort(archivos_simulacion_YADAV)
 
for (arc in archivos_simulacion_YADAV){
  

  estimacion_t_simulacion_DY_c1 <- read_csv(paste0('Traceplot_simulacion_phi/',arc)) %>% 
    mutate(iteracion=1:10000) %>% mutate(cadena = 1)
  
  estimacion_t_simulacion_DY_c2 <- read_csv(paste0('Traceplot_simulacion_phi/',arc))  %>% 
    mutate(iteracion=1:10000) %>% mutate(cadena = 2)
    
  estimacion_t_simulacion_DY <- rbind(estimacion_t_simulacion_DY_c1)#,estimacion_t_simulacion_DY_extremo_V3_V12_c2)
  
  
  df_long <- estimacion_t_simulacion_DY %>%
    pivot_longer(cols = starts_with("posterior"), 
                 names_to = "parametro", 
                 values_to = "valor")
  
  valores_reales <- data.frame(parametro=c("posterior_g1","posterior_g2","posterior_g3","posterior_g4","posterior_beta1","posterior_beta2","posterior_beta3","posterior_rho"),real=c(exp(1),1,1,1,0.8,0.7,5,0.5))
  
  df_long <- df_long %>% left_join(valores_reales,by='parametro')
  
  # Definir el orden de los parámetros en las facetas
  orden_parametros <- c("posterior_g1", "posterior_g2", "posterior_g3", "posterior_g4", 
                        "posterior_beta1", "posterior_beta2", "posterior_beta3", "posterior_rho")
  orden_parametros <- gsub("posterior_", "", orden_parametros)
  # Asegurarnos que 'cadena' esté como factor para diferenciar las dos cadenas
  df_long$cadenas <- factor(df_long$cadena, levels = c(1, 2), labels = c("Primera cadena", "Segunda cadena"))
  
  # Aseguramos que los parámetros estén en el orden correcto y quitamos "posterior"
  df_long$parametro <- factor(gsub("posterior_", "", df_long$parametro), levels = orden_parametros)
  
  df_long$parametro <- factor(df_long$parametro,labels=c("g1" = parse(text=TeX("$\\gamma_0$")), 
                                        "g2" = parse(text=TeX("$\\gamma_1$")), 
                                        "g3" = parse(text=TeX("$\\gamma_2$")), 
                                        "g4" = parse(text=TeX("$\\gamma_3$")), 
                                        "beta1" = parse(text=TeX("$\\beta_1$")), 
                                        "beta2" = parse(text=TeX("$\\beta_2$")), 
                                        "beta3" = parse(text=TeX("$\\beta_3$")), 
                                        "rho" = parse(text=TeX("$\\rho$"))  ))
  
  
  # Graficamos los traceplots
  p1 <- ggplot(df_long, aes(x = iteracion, y = valor, color = cadenas)) +
    geom_line(linewidth=0.5, alpha=0.3) +geom_hline(aes(yintercept = real), color = "blue", linetype = "dashed", size = 1)+ 
    facet_wrap(~parametro, scales = "free_y", 
               labeller = label_parsed,ncol = 4) +
    scale_color_manual(values = c("Primera cadena" = "black", "Segunda cadena" = "red"))+
     # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
     #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
    scale_x_continuous(breaks = c(0,5000,10000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
    theme_bw() +
    theme(legend.position = "none") +
    labs(x = "Iteración", y = "Valor")
  
  
  # Graficamos los traceplots
  p <- ggplot(df_long, aes(x = valor, color = cadenas)) +
    geom_histogram() +geom_vline(aes(xintercept = real), color = "blue", linetype = "dashed", size = 1)+ 
    facet_wrap(~parametro, scales = "free_x", 
               labeller = label_parsed,ncol = 4) +
    scale_color_manual(values = c("Primera cadena" = "black", "Segunda cadena" = "red"))+
     # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
     #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
    #scale_x_continuous(breaks = c(0,50000,100000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
    theme_bw() +
    theme(legend.position = "none") +
    labs(x = "Valor", y = arc)
  print(p)

}
```




```{r}


estimacion_t_simulacion_DY_extremo_V1_V11_c1 <- read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_DY_extremo_V1_V112_15_c1.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 1)

estimacion_t_simulacion_DY_extremo_V1_V11_c2 <- read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_DY_extremo_V1_V112_15_c2.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 2)
  
estimacion_t_simulacion_DY_extremo_V1_V11 <- rbind(estimacion_t_simulacion_DY_extremo_V1_V11_c1,estimacion_t_simulacion_DY_extremo_V1_V11_c2)



estimacion_t_simulacion_DY_extremo_V6_V16_c1 <- read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_DY_extremo_V6_V162_15_c1.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 1)

estimacion_t_simulacion_DY_extremo_V6_V16_c2 <- read_csv("Traceplot_simulacion_phi/estimacion_t_simulacion_DY_extremo_V6_V162_15_c2.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 2)
  
estimacion_t_simulacion_DY_extremo_V6_V16 <- rbind(estimacion_t_simulacion_DY_extremo_V6_V16_c1,estimacion_t_simulacion_DY_extremo_V6_V16_c2)#,estimacion_t_simulacion_DY_extremo_V4_V13_c2)





```



```{r}

df_long <- estimacion_t_simulacion_DY_extremo_V1_V11 %>%
  pivot_longer(cols = starts_with("posterior"), 
               names_to = "parametro", 
               values_to = "valor")

valores_reales <- data.frame(parametro=c("posterior_g1","posterior_g2","posterior_g3","posterior_g4","posterior_beta2","posterior_beta1","posterior_beta3","posterior_rho"),real=c(exp(1),1,1,1,0.7,0.8 ,5,0.5))

df_long <- df_long %>% left_join(valores_reales,by='parametro')

# Definir el orden de los parámetros en las facetas
orden_parametros <- c("posterior_g1", "posterior_g2", "posterior_g3", "posterior_g4", 
                      "posterior_beta2", "posterior_beta1", "posterior_beta3", "posterior_rho")
orden_parametros <- gsub("posterior_", "", orden_parametros)
# Asegurarnos que 'cadena' esté como factor para diferenciar las dos cadenas
df_long$cadenas <- factor(df_long$cadena, levels = c(1, 2), labels = c("Primera cadena", "Segunda cadena"))

# Aseguramos que los parámetros estén en el orden correcto y quitamos "posterior"
df_long$parametro <- factor(gsub("posterior_", "", df_long$parametro), levels = orden_parametros)

df_long$parametro <- factor(df_long$parametro,labels=c("g1" = parse(text=TeX("$\\gamma_0$")), 
                                      "g2" = parse(text=TeX("$\\gamma_1$")), 
                                      "g3" = parse(text=TeX("$\\gamma_2$")), 
                                      "g4" = parse(text=TeX("$\\gamma_3$")), 
                                      "beta1" = parse(text=TeX("$\\beta_1$")), 
                                      "beta2" = parse(text=TeX("$\\beta_2$")), 
                                      "beta3" = parse(text=TeX("$\\beta_3$")), 
                                      "rho" = parse(text=TeX("$\\rho$"))  ))


# Graficamos los traceplots
p1 <- ggplot(df_long, aes(x = iteracion, y = valor, color = cadenas)) +
  geom_line(linewidth=0.5, alpha=0.6) +geom_hline(aes(yintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_y", 
             labeller = label_parsed,ncol = 4) +
  scale_color_manual(values = c("Primera cadena" = "red", "Segunda cadena" = "#377eb8"))+
   # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
   #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
  scale_x_continuous(breaks = c(0,5000,10000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
p1
# Graficamos los traceplots
h1 <- ggplot(df_long, aes(x = valor, fill = cadenas)) +
  geom_histogram(position = "identity", bins = 25,alpha=0.6) +geom_vline(aes(xintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_x", 
             labeller = label_parsed,ncol = 4) +
  scale_fill_manual(values = c("Primera cadena" = "#e41a1c", "Segunda cadena" = "#377eb8"))+
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
h1
```




```{r}
df_long <- estimacion_t_simulacion_DY_extremo_V6_V16 %>%
  pivot_longer(cols = starts_with("posterior"), 
               names_to = "parametro", 
               values_to = "valor")

valores_reales <- data.frame(parametro=c("posterior_g1","posterior_g2","posterior_g3","posterior_g4","posterior_beta2","posterior_beta1","posterior_beta3","posterior_rho"),real=c(exp(1),1,1,1,0.7,0.8 ,5,0.5))

df_long <- df_long %>% left_join(valores_reales,by='parametro')

# Definir el orden de los parámetros en las facetas
orden_parametros <- c("posterior_g1", "posterior_g2", "posterior_g3", "posterior_g4", 
                      "posterior_beta2", "posterior_beta1", "posterior_beta3", "posterior_rho")
orden_parametros <- gsub("posterior_", "", orden_parametros)
# Asegurarnos que 'cadena' esté como factor para diferenciar las dos cadenas
df_long$cadenas <- factor(df_long$cadena, levels = c(1, 2), labels = c("Primera cadena", "Segunda cadena"))

# Aseguramos que los parámetros estén en el orden correcto y quitamos "posterior"
df_long$parametro <- factor(gsub("posterior_", "", df_long$parametro), levels = orden_parametros)

df_long$parametro <- factor(df_long$parametro,labels=c("g1" = parse(text=TeX("$\\gamma_0$")), 
                                      "g2" = parse(text=TeX("$\\gamma_1$")), 
                                      "g3" = parse(text=TeX("$\\gamma_2$")), 
                                      "g4" = parse(text=TeX("$\\gamma_3$")), 
                                      "beta1" = parse(text=TeX("$\\beta_1$")), 
                                      "beta2" = parse(text=TeX("$\\beta_2$")), 
                                      "beta3" = parse(text=TeX("$\\beta_3$")), 
                                      "rho" = parse(text=TeX("$\\rho$"))  ))


# Graficamos los traceplots
p2 <- ggplot(df_long, aes(x = iteracion, y = valor, color = cadenas)) +
  geom_line(linewidth=0.5, alpha=0.6) +geom_hline(aes(yintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_y", 
             labeller = label_parsed,ncol = 4) +
  scale_color_manual(values = c("Primera cadena" = "red", "Segunda cadena" = "#377eb8"))+
   # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
   #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
  scale_x_continuous(breaks = c(0,5000,10000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
p2
# Graficamos los traceplots
h2 <- ggplot(df_long, aes(x = valor, fill = cadenas)) +
  geom_histogram(position = "identity", bins = 25,alpha=0.6) +geom_vline(aes(xintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_x", 
             labeller = label_parsed,ncol = 4) +
  scale_fill_manual(values = c("Primera cadena" = "#e41a1c", "Segunda cadena" = "#377eb8"))+
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
h2
```


```{r}




y.grob <- textGrob("Valor", 
                   gp=gpar(), rot=90)

x.grob <- textGrob("Iteración", 
                   gp=gpar())

fig <- grid.arrange(p1,p2, left = y.grob, bottom = x.grob
)



ggsave("img/grafico_traceplot_simulacion_DY.pdf", plot = fig, width = 7.5, height = 5)


y.grob <- textGrob("Frecuencia", 
                   gp=gpar(), rot=90)

x.grob <- textGrob("Valor", 
                   gp=gpar())


fig <- fig <- grid.arrange(h1,h2, left = y.grob, bottom = x.grob
)
ggsave("img/grafico_histograma_simulacion_DY.pdf", plot = fig, width = 7.5, height = 5)



```
















# Estadísticos

## Distancia en Km

```{r}


# Función para convertir grados a radianes
deg2rad <- function(degrees) {
  return(degrees * pi / 180)
}

# Función para calcular la distancia utilizando la fórmula de Haversine
haversine <- function(lat1, lon1, lat2, lon2) {
  # Radio de la Tierra en kilómetros
  R <- 6371
  
  # Convertir las coordenadas de grados a radianes
  lat1 <- deg2rad(lat1)
  lon1 <- deg2rad(lon1)
  lat2 <- deg2rad(lat2)
  lon2 <- deg2rad(lon2)
  
  # Diferencias de latitudes y longitudes
  dlat <- lat2 - lat1
  dlon <- lon2 - lon1
  
  # Aplicar la fórmula de Haversine
  a <- sin(dlat / 2)^2 + cos(lat1) * cos(lat2) * sin(dlon / 2)^2
  c <- 2 * atan2(sqrt(a), sqrt(1 - a))
  
  # Calcular la distancia
  distance <- R * c
  return(distance)
}

# Crear un dataframe para todas las combinaciones posibles de filas
distancias <- cross_join(puntos,puntos) %>%
  # Calcular la distancia entre las locaciones
  mutate(distancia = haversine(lat.x, lon.x, lat.y, lon.y)) %>%
  select(id1 = id.x, id2 = id.y, distancia)  # Cambiar nombres de columnas para claridad

# Mostrar el dataframe con las distancias
distancias <- distancias %>% filter(id1!=id2) %>% arrange(distancia)

mean((distancias %>%  arrange(id1,id2))[1:(length(distancias$id1)/2),]$distancia)
```

```{r}
length(distancias$id1)/2
```




```{r}
# Proporción de ceros entre los sitios
datosPrecGuanacaste %>% 
  group_by(id) %>% 
  summarise(ceros= sum(ifelse(chirps==0,1,0)),unos= sum(ifelse(chirps!=0,1,0))) %>% 
  ungroup() %>% 
  mutate(proporcion_ceros = ceros/(unos+ceros)) %>% 
  arrange(proporcion_ceros)
```


## Media locaciones

```{r}

datosPrecGuanacaste <- read_csv("datosPrecGuanacaste.csv")
datosPrecGuanacaste$lon <- round(datosPrecGuanacaste$lon,3)
datosPrecGuanacaste$lat <- round(datosPrecGuanacaste$lat,3)



```

```{r}
puntos <- datosPrecGuanacaste %>% 
  group_by(id,lon,lat) %>% 
  summarise(n=n(),maxima_fecha = max(date),minima_fecha=min(date))

```





```{r}
# Ensure aut is in sf format
aut_sf <- gadm(country = 'CR', level = 2, path = '.') %>% st_as_sf()

# Extract the specific region for PacificoNorte
pacifico_norte_sf <- aut_sf %>% filter(NAME_1 == "Guanacaste")
media_locacion <- datosPrecGuanacaste %>% group_by(id,lon,lat) %>% 
  summarise(Mean=mean(chirps), SD=sd(chirps),P75 = quantile(chirps,0.75),IQR=IQR(chirps)) %>% 
  ungroup()
```


```{r}
media_locacion_pivot <- media_locacion %>% 
  pivot_longer(cols=c('Mean','SD','P75','IQR'),values_to = 'Valor')

p_valor <- ggplot(data = pacifico_norte_sf) +
    geom_sf(fill = "white", color = "black")+ 
  geom_point(data = media_locacion_pivot, aes(x = lon, y = lat, color = Valor), size = 5) +  # Dibujar los puntos
  scale_color_gradient2( low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", midpoint = mean(media_locacion$Mean))+theme_bw()+
  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "Valor"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  )+facet_wrap(~name)
p_valor


```


```{r}
p_media <- ggplot(data = pacifico_norte_sf) +
    geom_sf(fill = "white", color = "black")+ 
  geom_point(data = media_locacion, aes(x = lon, y = lat, color = Mean), size = 5) +  # Dibujar los puntos
  scale_color_gradient2( low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", midpoint = mean(media_locacion$Mean))+theme_bw()+
  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "Mean"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) 
p_media


p_desv <- ggplot(data = pacifico_norte_sf) +
    geom_sf(fill = "white", color = "black")+ 
  geom_point(data = media_locacion, aes(x = lon, y = lat, color = SD), size = 5,) +  # Dibujar los puntos
   scale_color_gradient2(low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", midpoint = mean(media_locacion$SD))+theme_bw()+
  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "SD"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  )

p_C75 <- ggplot(data = pacifico_norte_sf) +
    geom_sf(fill = "white", color = "black")+ 
  geom_point(data = media_locacion, aes(x = lon, y = lat, color = P75), size = 5,) +  # Dibujar los puntos
   scale_color_gradient2(low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", midpoint = mean(media_locacion$P75))+theme_bw()+
  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "P75"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  )
p_C75
p_iqr<- ggplot(data = pacifico_norte_sf) +
    geom_sf(fill = "white", color = "black")+ 
  geom_point(data = media_locacion, aes(x = lon, y = lat, color = IQR), size = 5,) +  # Dibujar los puntos
   scale_color_gradient2(low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", midpoint = mean(media_locacion$IQR))+theme_bw()+
  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "IQR"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  )
p_iqr


#009392,#72aaa1,#b1c7b3,#f1eac8,#e5b9ad,#d98994,#d0587e
  #009392,#39b185,#9ccb86,#e9e29c,#eeb479,#e88471,#cf597e
#008080,#70a494,#b4c8a8,#f6edbd,#edbb8a,#de8a5a,#ca562c

p_estadisticos1 <- grid.arrange(p_media, p_desv, ncol = 2, widths = c(0.5, 0.5))
p_estadisticos2 <- grid.arrange(p_C75, p_iqr, ncol = 2, widths = c(0.5, 0.5))
p_estadisticos  <- grid.arrange(p_estadisticos1, p_estadisticos2, ncol = 2)

ggsave("img_articulo/grafico_locaciones_media.pdf", plot = p_estadisticos1, width = 10, height = 5)
ggsave("img_articulo/grafico_locaciones_med.pdf", plot = p_estadisticos2, width = 10, height = 5)

```


## Extremograma

```{r}
Generadora_de_datos <- function(datos.lluvia.unidos,quantile_de_interes){

  
  #################################################################################
  
  datos.lluvia.unidos.columnas <- datos.lluvia.unidos%>% mutate(identificador=paste(lon,lat))%>% arrange(identificador) %>%dplyr::select(identificador,chirps) %>%  pivot_wider(names_from = identificador,values_from=chirps)
  
  datos.lluvia.pareto <- data.frame(1:976)
  
  for(k in 1:length(names(datos.lluvia.unidos.columnas))){
   datos.lluvia.pareto <-  cbind(datos.lluvia.pareto,datos.lluvia.unidos.columnas[k][[1]][[1]])
    
  }
  
  datos.lluvia.pareto <- datos.lluvia.pareto[-1]
  names(datos.lluvia.pareto) <- names(datos.lluvia.unidos.columnas)

  # Compute local mean and XXquantile
  quantile_anomaly <- rep(NA, length(datos.lluvia.pareto[1,]))
  mean_anomaly <- rep(NA, length(datos.lluvia.pareto[1,]))
  
  # Set quantile level
  quantileLevel <- quantile_de_interes # AQUI SE CAMBIA EL CUANTIL PARA EL GRÁFICO
  for(i in 1:length(quantile_anomaly)){
    quantile_anomaly[i] <- quantile(datos.lluvia.pareto[,i], quantileLevel, na.rm = TRUE)
    mean_anomaly[i] <- mean(datos.lluvia.pareto[,i], na.rm = TRUE)
  }
  #print("Local mean:")
  #summary(mean_anomaly)
  #print(paste0("Local empirical " ,quantileLevel," quantile:"))
  #summary(quantile_anomaly)
  return(list(datos.lluvia.pareto,quantile_anomaly))
}



# Function to estimate the empirical extromagram or coefficient between two locations
computeExtremalCoeff <- function(pos1, pos2, database, local_quantiles) {
  theta <- length(which((database[, pos1] > local_quantiles[pos1] & !is.na(database[,pos1])) &
                          (database[, pos2] > local_quantiles[pos2] & !is.na(database[,pos2]))
  )) /
    length(which((database[, pos1] > local_quantiles[pos1] & !is.na(database[, pos1]))))
  return(theta)
}


Grafico_coeficiente <- function(datos.lluvia.pareto,quantile_anomaly,quantile_de_interes){

Coordenadas <- data.frame(Coordenadas=names(datos.lluvia.pareto)) %>% 
  separate(Coordenadas,sep=" ",into = c("lon","lat")) %>% 
  mutate(lon=as.numeric(lon),lat=as.numeric(lat))

# Cálculo del coeficiente para todas las distancias:
subset_location_size <- length(Coordenadas[,1])
# Compute all possible pairwise combinations
pairs_combination_indexes <- expand.grid(1:subset_location_size,1:subset_location_size)

index_for_estimation <- 1:subset_location_size

# Create vector of empirical extremogram
empirical_extremogram <- rep(NA, length(pairs_combination_indexes[,1]))

# Compute empirical extremogram for each pair of locations
for(k in 1:length(empirical_extremogram)){
  empirical_extremogram[k] <- computeExtremalCoeff(pairs_combination_indexes[k,1], pairs_combination_indexes[k,2], datos.lluvia.pareto[,index_for_estimation], quantile_anomaly[index_for_estimation])
}


# El código siguiente es una forma de calcula la distancia de una forma más adecuada.

# Compute vector of distance between each pairs
# distances_between_pairs <- sqrt((Coordenadas[index_for_estimation[pairs_combination_indexes[,1]],1] - Coordenadas[index_for_estimation[pairs_combination_indexes[,2]],1])^2 +
#                  (Coordenadas[index_for_estimation[pairs_combination_indexes[,1]],2] - Coordenadas[index_for_estimation[pairs_combination_indexes[,2]],2])^2)

distances_between_pairs <- haversine(Coordenadas[index_for_estimation[pairs_combination_indexes[,1]],2], Coordenadas[index_for_estimation[pairs_combination_indexes[,1]],1], Coordenadas[index_for_estimation[pairs_combination_indexes[,2]],2], Coordenadas[index_for_estimation[pairs_combination_indexes[,2]],1])



# Compute orientation of each pairs
matrixOfAngles <- atan((Coordenadas[index_for_estimation[pairs_combination_indexes[,1]],2] - Coordenadas[index_for_estimation[pairs_combination_indexes[,2]],2]) /
                         (Coordenadas[index_for_estimation[pairs_combination_indexes[,1]],1] - Coordenadas[index_for_estimation[pairs_combination_indexes[,2]],1])) / pi * 180
matrixOfAngles[is.nan(matrixOfAngles)] <- 0

# Store results in data frame for easier plotting
estimates <- data.frame(extremogram = empirical_extremogram[!is.nan(empirical_extremogram)], dist = distances_between_pairs[!is.nan(empirical_extremogram)], angle = matrixOfAngles[!is.nan(empirical_extremogram)],
                        x = distances_between_pairs[!is.nan(empirical_extremogram)] * cos(matrixOfAngles[!is.nan(empirical_extremogram)]), y = distances_between_pairs[!is.nan(empirical_extremogram)] * sin(matrixOfAngles[!is.nan(empirical_extremogram)]))

# En el gráfico anterior, podemos observar que el estimador del coeficiente para un umbral actual en código del cuantil 99.
grafico <- ggplot(data = estimates, aes(x = dist, y = extremogram)) + geom_point() + geom_smooth(se = FALSE) + ylim(0,1) +theme_bw()+labs(x = "Distancia (Km)", y = bquote(chi(.(quantile_de_interes))))
return(grafico)


}
```


```{r}


cuantil <- 0.95
datos <- Generadora_de_datos(datosPrecGuanacaste,cuantil)
g1 <- Grafico_coeficiente(datos[[1]],datos[[2]],cuantil)

cuantil <- 0.975
datos <- Generadora_de_datos(datosPrecGuanacaste,cuantil)
g2 <- Grafico_coeficiente(datos[[1]],datos[[2]],cuantil)


cuantil <- 0.99
datos <- Generadora_de_datos(datosPrecGuanacaste,cuantil)
g3 <- Grafico_coeficiente(datos[[1]],datos[[2]],cuantil)
extremograma <- grid.arrange(g1,g3,ncol=2)

ggsave("grafico_extremograma.pdf", plot = extremograma, width = 10, height = 5)
```


# Exploratorios de cola


```{r}
proceso_D7_estimacion <- function(params_covariables, params_parametros, nsites, m, cov, dist_mat,beta1=0.5) {
  # Asignar los parámetros de covariables
  y_train_gamma_auxiliar <- params_covariables
  
  # Asignar los parámetros de los otros valores
  y_train_phi_auxiliar <- params_parametros[1]
  y_train_sigma_auxiliar <- params_parametros[2]
  y_train_beta3_auxiliar <- params_parametros[3]
  y_train_rho_auxiliar <- params_parametros[4]
  
  # Inicialización de X_train_auxiliar usando el código anterior
  X_train_auxiliar <- matrix(0, ncol = nsites, nrow = m)
  
  # Simular X3 usando la función simular_X3
  X3_auxiliar_completo <- simular_X3(m, y_train_rho_auxiliar, y_train_beta3_auxiliar, nsites, dist_mat)
  
  # Simular X1 usando la función simular_X1
  X2_auxiliar <- simular_logAR1(m, y_train_phi_auxiliar, y_train_sigma_auxiliar)
  
  X1_auxiliar <- simular_X1(m, beta1)
  # Bucle para calcular las covariables y valores para cada sitio
  for (sitio in 1:nsites) {
    # Simular X2 usando la función simular_logAR1
    
    
    # Obtener el valor correspondiente de X3 para el sitio
    X3_auxiliar <- X3_auxiliar_completo[, sitio]
    
    # Calcular la covariable auxiliar
    covariables_auxiliar <- calculo_covariable(cov[sitio, ], y_train_gamma_auxiliar)
    
    # Calcular los valores auxiliares
    auxi <- X2_auxiliar * X3_auxiliar * covariables_auxiliar * X1_auxiliar
    
    # Calcular el cuantil 75
    cuantil_75 <- quantile(auxi, 0)
    
    # Asignar el valor mínimo entre auxi y el cuantil 75
    X_train_auxiliar[,sitio ] <- ifelse(auxi < cuantil_75, cuantil_75, auxi)
  }

  # Retornar la matriz final
  return(X_train_auxiliar)
}

dist_mat_ejemplo <- matrix(c(0,0.5,0.5,0),nrow=2,byrow = T)
cov <- matrix(c(1,1,1,0.5),nrow=2,byrow = T)

computeExtremalCoeff <- function(pos1, pos2, database, local_quantiles) {
  theta <- length(which((database[, pos1] > local_quantiles[pos1] & !is.na(database[,pos1])) &
                          (database[, pos2] > local_quantiles[pos2] & !is.na(database[,pos2]))
  )) /
    length(which((database[, pos1] > local_quantiles[pos1] & !is.na(database[, pos1]))))
  return(theta)
}


Y <- proceso_D7_estimacion(c(1,2),c(0.5,1,5,1),2,10000,cov, dist_mat_ejemplo)
coeficiente <- c()
mu <- c()
for (k in seq(0,0.999,0.001)) {
  qs <- sapply(1:2,function(i){quantile(Y[,i],k)})
  coeficiente <- c(coeficiente,computeExtremalCoeff(1,2,Y,qs))
  mu <- c(mu,k)
  
}
result <- data.frame(x=11,mu,coeficiente)

Y <- proceso_D7_estimacion(c(1,2),c(0.5,1,5,1),2,10000,cov, dist_mat_ejemplo,1)
coeficiente <- c()
mu <- c()
for (k in seq(0,0.999,0.001)) {
  qs <- sapply(1:2,function(i){quantile(Y[,i],k)})
  coeficiente <- c(coeficiente,computeExtremalCoeff(1,2,Y,qs))
  mu <- c(mu,k)
  
}
result <- rbind(result,data.frame(x=12,mu,coeficiente))


Y <- proceso_D7_estimacion(c(1,2),c(0.5,1,5,1),2,10000,cov, dist_mat_ejemplo,0.1)
coeficiente <- c()
mu <- c()
for (k in seq(0,0.999,0.001)) {
  qs <- sapply(1:2,function(i){quantile(Y[,i],k)})
  coeficiente <- c(coeficiente,computeExtremalCoeff(1,2,Y,qs))
  mu <- c(mu,k)
  
}
result <- rbind(result,data.frame(x=13,mu,coeficiente))





Y <- proceso_D7_estimacion(c(1,2),c(0.1,2,5,1),2,10000,cov, dist_mat_ejemplo)
coeficiente <- c()
mu <- c()
for (k in seq(0,0.999,0.001)) {
  qs <- sapply(1:2,function(i){quantile(Y[,i],k)})
  coeficiente <- c(coeficiente,computeExtremalCoeff(1,2,Y,qs))
  mu <- c(mu,k)
  
}
result <- rbind(result,data.frame(x=21,mu,coeficiente))



Y <- proceso_D7_estimacion(c(1,2),c(0.1,2,5,1),2,10000,cov, dist_mat_ejemplo,1)
coeficiente <- c()
mu <- c()
for (k in seq(0,0.999,0.001)) {
  qs <- sapply(1:2,function(i){quantile(Y[,i],k)})
  coeficiente <- c(coeficiente,computeExtremalCoeff(1,2,Y,qs))
  mu <- c(mu,k)
  
}
result <- rbind(result,data.frame(x=22,mu,coeficiente))




Y <- proceso_D7_estimacion(c(1,2),c(0.1,2,5,1),2,10000,cov, dist_mat_ejemplo,0.1)
coeficiente <- c()
mu <- c()
for (k in seq(0,0.999,0.001)) {
  qs <- sapply(1:2,function(i){quantile(Y[,i],k)})
  coeficiente <- c(coeficiente,computeExtremalCoeff(1,2,Y,qs))
  mu <- c(mu,k)
  
}
result <- rbind(result,data.frame(x=23,mu,coeficiente))





result$x <- factor(result$x)
ggplot(result)+geom_line(aes(mu,coeficiente,group=x,color=x))
```

# Aplicación

## Calculo de error




```{r}
set.seed(1)

# Leer el archivo CSV
datos_guanacaste <- read.csv('datosPrecGuanacaste.csv')
covariables_guanacaste <- read.csv('covariables_guanacaste.csv')
# Redondear latitud y longitud
datos_guanacaste$lon <- round(datos_guanacaste$lon, 3)
datos_guanacaste$lat <- round(datos_guanacaste$lat, 3)

# Ordenar por fecha
datos_guanacaste <- datos_guanacaste[order(datos_guanacaste$date), ]

# Agrupar por latitud y longitud
loc <- covariables_guanacaste
loc <- loc[order(loc$lat, loc$lon, decreasing = c(T, F)), ]
loc <- loc[, c('lon', 'lat', 'alt')]

# Filtrar datos de entrenamiento
locaciones_completas <- loc[loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 10.3 & loc$lat < 10.8, ]
nsites <- nrow(locaciones_completas)



# Filtrar datos de prueba (test)
filtradora <- locaciones_completas %>% 
  mutate(lonlat = paste0(lon,lat))

locaciones_test <- covariables_guanacaste %>% 
  filter(!(paste0(lon,lat) %in% filtradora$lonlat))
  
  
# Concatenar los datos de prueba
locaciones_test <- locaciones_test[order(locaciones_test$lat, locaciones_test$lon, decreasing = c(T, F)), ]

# Concatenar datos de entrenamiento y prueba
locaciones_train_test <- covariables_guanacaste
locaciones_train_test <- locaciones_train_test[order(locaciones_train_test$lat, locaciones_train_test$lon, decreasing = c(T, F)), ]

# Renombrar columnas
locaciones_train_test$lat_x <- locaciones_train_test$lat
locaciones_train_test$lon_x <- locaciones_train_test$lon
locaciones_train_test <- locaciones_train_test %>% dplyr::select(-lat,-lon)



# Hacer merge con locaciones_test
locaciones_train_test <- locaciones_train_test  %>% mutate(lonlat=paste0(lat_x,lon_x))%>% left_join( locaciones_test %>% mutate(lonlat=paste0(lat,lon)), "lonlat")

# Agregar la columna 'tipo' para indicar si es 'train' o 'test'
locaciones_train_test$tipo <- ifelse(is.na(locaciones_train_test$lon), 'train', 'test')

# Seleccionar columnas relevantes
locaciones_train_test <- locaciones_train_test[, c('lon_x', 'lat_x','alt.x', 'tipo')]

# Renombrar columnas
colnames(locaciones_train_test)[1:3] <- c('lon', 'lat','alt')

# Obtener el número de sitios en el conjunto de datos final
nsites_train_test <- nrow(locaciones_train_test)


# Definir las covariables espaciales
Z1 <- locaciones_completas$lon  # primera covariable espacial
Z2 <- locaciones_completas$lat  # segunda covariable espacial
Z12 <- locaciones_completas$lon^2  # primera covariable espacial al cuadrado
Z22 <- locaciones_completas$lat^2  # segunda covariable espacial al cuadrado
Z3 <- locaciones_completas$alt  # tercera covariable (altitud)
Z32 <- locaciones_completas$alt^2  # altitud al cuadrado

# Definir las covariables espaciales para el conjunto de entrenamiento y prueba
Z1_train_test <- locaciones_train_test$lon  # primera covariable espacial
Z2_train_test <- locaciones_train_test$lat  # segunda covariable espacial
Z12_train_test <- locaciones_train_test$lon^2  # primera covariable espacial al cuadrado
Z22_train_test <- locaciones_train_test$lat^2  # segunda covariable espacial al cuadrado
Z3_train_test <- locaciones_train_test$alt  # tercera covariable (altitud)
Z32_train_test <- locaciones_train_test$alt^2  # altitud al cuadrado

# Función para normalización Min-Max
normalize_min_max <- function(x,minz,maxz) {
  return((x -minz) / (maxz- minz))
}

# Normalizar las covariables
a <- min(Z1)
b <- max(Z1)
Z1 <- normalize_min_max(Z1,a,b)
Z1_train_test <- normalize_min_max(Z1_train_test,a,b)
a <- min(Z2)
b <- max(Z2)
Z2 <- normalize_min_max(Z2,a,b)
Z2_train_test <- normalize_min_max(Z2_train_test,a,b)

a <- min(Z12)
b <- max(Z12)

Z12 <- normalize_min_max(Z12,a,b)
Z12_train_test <- normalize_min_max(Z12_train_test,a,b)

a <- min(Z22)
b <- max(Z22)


Z22 <- normalize_min_max(Z22,a,b)
Z22_train_test <- normalize_min_max(Z22_train_test,a,b)

a <- min(Z3)
b <- max(Z3)

Z3 <- normalize_min_max(Z3,a,b)
Z3_train_test <- normalize_min_max(Z3_train_test,a,b)

a <- min(Z32)
b <- max(Z32)

Z32 <- normalize_min_max(Z32,a,b)
Z32_train_test <- normalize_min_max(Z32_train_test,a,b)

# Calcular la matriz de distancia entre los sitios
dist_mat <- as.matrix(dist(locaciones_completas[, c("lon", "lat")]))  # matriz de distancia (nsites x nsites)
dist_mat_train_test <- as.matrix(dist(locaciones_train_test[, c("lon", "lat")]))  # matriz de distancia para train test

# Mostrar el rango de la distancia para verificar el valor máximo
rho_upper_range <- 2 * max(dist_mat)

# Crear la matriz de covariables para el conjunto de datos de entrenamiento
cov_original <- cbind(1, Z1, Z2, Z3, Z12, Z22, Z32)  # matriz de diseño (nsites x 7)

# Crear la matriz de covariables para el conjunto de datos de entrenamiento y prueba
cov_original_train_test <- cbind(1, Z1_train_test, Z2_train_test, Z3_train_test, Z12_train_test, Z22_train_test, Z32_train_test)  # matriz de diseño (nsites x 7)

# Calcular el valor de m
m <- nrow(datos_guanacaste) / nrow(loc)

# Mostrar información de las localizaciones
cat(nsites, "locaciones\n")
cat(m, "en tiempo\n")

cat(nsites_train_test, "locaciones en train test\n")
cat(m, "en tiempo\n")

# Filtrar los datos para entrenamiento y prueba
datos_guanacaste_filtrados <- merge(datos_guanacaste, locaciones_completas, by = c("lon", "lat"))
datos_guanacaste_filtrados_train_test <- merge(datos_guanacaste, locaciones_train_test, by = c("lon", "lat"))

#########################################################################
# Inicializar la matriz de covariables para el conjunto de entrenamiento
X_train_guanacaste <- matrix(0, nrow = m, ncol = nsites)

for (sitio in 1:nsites) {
  lon_actual <- locaciones_completas$lon[sitio]
  lat_actual <- locaciones_completas$lat[sitio]
  
  # Filtrar los datos para el sitio actual
  auxi <- datos_guanacaste_filtrados[datos_guanacaste_filtrados$lon == lon_actual & datos_guanacaste_filtrados$lat == lat_actual, ]
  auxi <- auxi[order(auxi$date), ]$chirps  # Ordenar por fecha y extraer los valores de 'chirps'
  
  # Calcular el cuantil 75
  cuantil_75 <- quantile(auxi, 0.75)
  
  # Asignar el valor a la matriz X_train_guanacaste
  X_train_guanacaste[,sitio] <- ifelse(auxi < cuantil_75, cuantil_75, auxi)
}



########################################################################


# Inicializar la matriz de covariables para el conjunto de entrenamiento y prueba
X_train_guanacaste_train_test <- matrix(0, nrow = m, ncol = nsites_train_test)

for (sitio in 1:nsites_train_test) {
  lon_actual <- locaciones_train_test$lon[sitio]
  lat_actual <- locaciones_train_test$lat[sitio]
  
  # Filtrar los datos para el sitio actual
  auxi <- datos_guanacaste_filtrados_train_test[datos_guanacaste_filtrados_train_test$lon == lon_actual & datos_guanacaste_filtrados_train_test$lat == lat_actual, ]
  auxi <- auxi[order(auxi$date), ]$chirps  # Ordenar por fecha y extraer los valores de 'chirps'
  
  # Calcular el cuantil 75
  cuantil_75 <- quantile(auxi, 0.75)
  
  # Asignar el valor a la matriz X_train_guanacaste_train_test
  X_train_guanacaste_train_test[,sitio] <- ifelse(auxi < cuantil_75, cuantil_75, auxi)
}



```
```{r}
locaciones_extras_arriba <- loc[loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 10.749 & loc$lat < 10.9, ]
locaciones_extras_abajo <- loc[loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 10.2 & loc$lat < 10.3, ]
punta_abajo <- loc[loc$lon > -85.7 & loc$lon < -85.2 & loc$lat < 9.8, ]
punta_arriba <- loc[loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 11.1, ]
punta_derecha <- loc[loc$lon > -84.9, ]
punta_izquierda <- loc[loc$lon < -85.8, ]
 locaciones_test_f<- rbind(locaciones_extras_arriba, locaciones_extras_abajo, punta_abajo, punta_arriba, punta_derecha, punta_izquierda)
locaciones_test_f <- locaciones_test_f[order(locaciones_test_f$lat, locaciones_test_f$lon, decreasing = c(T, F)), ]
locaciones_test_f <- locaciones_test_f %>% mutate(lonlat=paste0(lon,lat))
```


```{r}
vect_test <- paste0('s',(locaciones_train_test %>% 
  mutate(id=1:n()) %>% 
  dplyr::filter(tipo=='test'))$id)

vect_train <- paste0('s',(locaciones_train_test %>% 
  mutate(id=1:n()) %>% 
  dplyr::filter(tipo=='train'))$id)

load("traceplot_errores_phi_test_final.RData")

load("traceplot_errores_phi_train_final.RData")

vect_test_reducido <- paste0('s', c(1,2,11,13,24,34,54,57,59,61,70,76,78,81,82))


vect_test_original <- paste0('s',(locaciones_train_test %>% 
  mutate(id=1:n()) %>% 
  dplyr::filter(paste0(lon,lat) %in% locaciones_test_f$lonlat))$id)

```





```{r}
# Test


tabla_resultados <- function(vects,metrica_n,df){
  
  
  errores <- as.matrix(df[,vects])
  if(grepl('med',metrica_n)){
    medianas <- rowMedians(errores)
  }else{
    medianas <- rowMeans(errores)
  }
  
  
  tabla <- df %>% 
    mutate(metrica = medianas) %>% 
    filter(error==metrica_n) %>% 
    arrange(metrica) %>% 
    dplyr::select(modelo,metrica)
  
  tabla <- tabla%>% 
    separate(modelo,c('C1','C2'),' ') 
  
  print((tabla %>% 
    filter(C1 != 'DY') %>% mutate(modelo =paste0(C1,C2)))[1,'modelo'])
  
  tabla <- tabla %>% 
    pivot_wider(
      names_from = C2,
      values_from = metrica
    ) %>%
    arrange(C1) %>%
    rename(D = C1) %>% 
    dplyr::select(any_of(c("D",paste0("M", 1:8)))) 
  
  tabla_fmt <- tabla
  tabla_fmt[ , -1] <- lapply(tabla_fmt[ , -1], function(x) ifelse(is.na(x), "--", formatC(x, format = "f", digits = 3)))
  
  for (i in 1:nrow(tabla_fmt)) {
    cat(ifelse(i == 1, "", " "), paste(tabla_fmt[i, ], collapse = " & "), " \\\\\n &")
  }
}

tabla_resultados(vect_train,'abs_mean',df_errores_train)
tabla_resultados(vect_test,'abs_mean',df_errores_test)
tabla_resultados(vect_train,'sqr_mean',df_errores_train)
tabla_resultados(vect_test,'sqr_mean',df_errores_test)

tabla_resultados(vect_test_reducido,'sqr_mean',df_errores_train)


tabla_resultados(vect_train,'sqr_mean',df_errores_train)
tabla_resultados(vect_test,'sqr_mean',df_errores_test)
tabla_resultados(vect_test_reducido,'sqr_mean',df_errores_test)
tabla_resultados(vect_test_original,'sqr_mean',df_errores_test)


tabla_resultados(vect_train,'abs_mean',df_errores_train)
tabla_resultados(vect_test,'abs_mean',df_errores_test)
tabla_resultados(vect_test_reducido,'abs_mean',df_errores_test)
tabla_resultados(vect_test_original,'abs_mean',df_errores_test)
tabla_resultados(c('s1','s2','s11','s13','s24','s34','s54'),'abs_mean')
tabla_resultados(c('s1','s2','s11','s13','s24','s34','s54','s57','s59','s61','s70','s76','s78'),'abs_mean')



tabla_resultados(vect_train,'abs_median',df_errores_train)
tabla_resultados(vect_test,'abs_median',df_errores_test)
tabla_resultados(vect_test_reducido,'abs_median',df_errores_test)
tabla_resultados(vect_test_original,'abs_median',df_errores_test)

tabla_resultados(vect_train,'sqr_median',df_errores_train)
tabla_resultados(vect_test,'sqr_median',df_errores_test)
tabla_resultados(vect_test_reducido,'sqr_median')
tabla_resultados(vect_test_original,'sqr_median')

# tabla_resultados(vect_train,'abs_mean')
# tabla_resultados(vect_test,'abs_mean')
# tabla_resultados(vect_test_reducido,'abs_mean')


# tabla_resultados(vect_test_reducido,'abs_mean')
# tabla_resultados(vect_test_reducido,'abs_median')
#tabla_resultados(vect_test_reducido,'sqr_mean')
#tabla_resultados(vect_test_reducido,'sqr_median')
# 
# 
# tabla_resultados(vect_test,'abs_mean')
# tabla_resultados(vect_test,'sqr_mean')
#tabla_resultados(vect_test,'abs_median')
#tabla_resultados(vect_test,'sqr_median')



#tabla_resultados(vect_train,'abs_median')
#tabla_resultados(vect_train,'sqr_median')
```



```{r}
modelos_menor_error <- rep(NA, 83)  # Un vector de longitud 83

# Paso 2: Para cada columna 's1' a 's83', identificar el modelo con menor error
for (i in 1:83) {
  colname <- paste0("s", i)  # Generamos el nombre de la columna s1, s2, ..., s83
  min_error_idx <- which.min(df_errores[[colname]])  # Encuentra el índice del mínimo error en la columna
  modelos_menor_error[i] <- df_errores$modelo[min_error_idx]  # Guarda el modelo con el menor error
}

# Paso 3: Crear una tabla con el modelo con menor error por cada columna
tabla_menor_error <- data.frame(columna = paste0("s", 1:83), modelo_con_menor_error = modelos_menor_error)

# Paso 4: Contar cuántas veces cada modelo tiene el menor error
conteo_modelos <- table(tabla_menor_error$modelo_con_menor_error)

conteo_modelos
```


## Cálculo WIS


```{r}
# Train
library(stringr)
library(dplyr)
library(tidyr)

archivos <- dir('calculo_WIS')

# filtrar archivos de interés
archivos_cuantiles <- archivos[
  stringr::str_detect(archivos, 'train') & stringr::str_detect(archivos, 'quantile') 
]

df_WIS_modelos <- data.frame()

for (arc in archivos_cuantiles) {
  
  load(paste0('calculo_WIS/', arc))
  
  vector_WIS <- c()
  
  for (lloc in as.integer(stringr::str_replace(vect_train, 's', ''))) {
    for (lt in unique(df_IS$t)) {
      
      observacion <- df_IS %>% 
        filter(variable == lloc, t == lt)
      
      if (nrow(observacion) > 0) {
        WIS_y <- 1/(nrow(observacion)+0.5) * (
          abs(observacion$y[1] - observacion$m[1]) +
          sum(observacion$IS * observacion$alpha / 2)
        )
        
        vector_WIS <- c(vector_WIS, WIS_y)
      }
    }
  }
  
  # extraer D y M (soporta quantile, DY, DZ, etc.)
  modelo_info <- stringr::str_match(
    arc, "(?:quantile)?(D[0-9]+|DY|DZ)-(M[0-9]+)"
  )
  
  D_val <- modelo_info[2]
  M_val <- modelo_info[3]
  
  # guardar resultado
  WIS_modelo <- data.frame(
    D = D_val,
    M = M_val,
    wis = mean(vector_WIS)
  )
  
  df_WIS_modelos <- rbind(df_WIS_modelos, WIS_modelo)
}

# ---------------------------
# completar combinaciones faltantes
# ---------------------------

D_vals <- c(paste0("D", 1:8), "DY")
M_vals <- paste0("M", 1:7)

df_WIS_modelos <- df_WIS_modelos %>%
  complete(D = D_vals, M = M_vals, fill = list(wis = 0))

# ---------------------------
# pasar a formato ancho
# ---------------------------

tabla <- df_WIS_modelos %>%
  pivot_wider(names_from = M, values_from = wis) %>%
  arrange(factor(D, levels = D_vals))

# ---------------------------
# formatear decimales
# ---------------------------

tabla_fmt <- tabla
tabla_fmt[,-1] <- lapply(tabla_fmt[,-1], function(x) sprintf("%.3f", x))

# ---------------------------
# imprimir formato LaTeX
# ---------------------------

for (i in 1:nrow(tabla_fmt)) {
  
  fila <- tabla_fmt[i,]
  
  linea <- paste0(
    ifelse(i == 1, "", " & "),
    fila$D, " & ",
    paste(fila[,-1], collapse = " & "),
    " \\\\"
  )
  
  cat(linea, "\n")
}




```


```{r}
df_errores_train
```

## Traceplot

```{r}

estimacion_t_simulacion_DY_extremo_V1 <- read_csv("C:/Users/XPC/Desktop/NEURBAYES_archivos/bayesflow/Reporteria/Traceplot_aplicacion_phi_final/trace_covariables_DY2_aplicacion_M5.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 1)

df_long <- estimacion_t_simulacion_DY_extremo_V1 %>%
  pivot_longer(cols = starts_with("posterior"), 
               names_to = "parametro", 
               values_to = "valor")

orden_parametros <- c("posterior_g1", "posterior_g2", "posterior_g3", "posterior_g4","posterior_g5", 
                      "posterior_beta2", "posterior_beta1", "posterior_beta3", "posterior_rho")

medias <- estimacion_t_simulacion_DY_extremo_V1[,orden_parametros] %>%colMeans() 

valores_reales <- data.frame(parametro=c("posterior_g1","posterior_g2","posterior_g3","posterior_g4","posterior_g5","posterior_beta2","posterior_beta1","posterior_beta3","posterior_rho"),real=medias)

df_long <- df_long %>% left_join(valores_reales,by='parametro')

# Definir el orden de los parámetros en las facetas

orden_parametros <- gsub("posterior_", "", orden_parametros)
# Asegurarnos que 'cadena' esté como factor para diferenciar las dos cadenas
df_long$cadenas <- factor(df_long$cadena, levels = c(1, 2), labels = c("Primera cadena", "Segunda cadena"))

# Aseguramos que los parámetros estén en el orden correcto y quitamos "posterior"
df_long$parametro <- factor(gsub("posterior_", "", df_long$parametro), levels = orden_parametros)

df_long$parametro <- factor(df_long$parametro,labels=c("g1" = parse(text=TeX("$\\gamma_1$")), 
                                      "g2" = parse(text=TeX("$\\gamma_2$")), 
                                      "g3" = parse(text=TeX("$\\gamma_3$")), 
                                      "g4" = parse(text=TeX("$\\gamma_4$")), 
                                      "g5" = parse(text=TeX("$\\gamma_5$")), 
                                      "beta1" = parse(text=TeX("$\\beta_1$")), 
                                      "beta2" = parse(text=TeX("$\\beta_2$")), 
                                      "beta3" = parse(text=TeX("$\\beta_3$")), 
                                      "rho" = parse(text=TeX("$\\rho$"))  ))


# Graficamos los traceplots
p1 <- ggplot(df_long, aes(x = iteracion, y = valor, color = cadenas)) +
  geom_line(linewidth=0.5, alpha=0.6) +geom_hline(aes(yintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_y", 
             labeller = label_parsed,ncol = 4) +
  scale_color_manual(values = c("Primera cadena" = "red", "Segunda cadena" = "#377eb8"))+
   # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
   #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
  scale_x_continuous(breaks = c(0,5000,10000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
p1
# Graficamos los traceplots
h1 <- ggplot(df_long, aes(x = valor, fill = cadenas)) +
  geom_histogram(position = "identity", bins = 25,alpha=0.6) +geom_vline(aes(xintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_x", 
             labeller = label_parsed,ncol = 4) +
  scale_fill_manual(values = c("Primera cadena" = "#e41a1c", "Segunda cadena" = "#377eb8"))+
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
```


```{r}
estimacion_t_simulacion_D8_extremo_V1 <-trace_covariables_D8_aplicacion_M4 <- read_csv("C:/Users/XPC/Desktop/NEURBAYES_archivos/bayesflow/Reporteria/Traceplot_aplicacion_phi_final/trace_covariables_D4_aplicacion_M4.csv") %>% 
  mutate(iteracion=1:10000) %>% mutate(cadena = 1)


df_long <- estimacion_t_simulacion_D8_extremo_V1 %>%
  pivot_longer(cols = starts_with("posterior"), 
               names_to = "parametro", 
               values_to = "valor")




orden_parametros <- c("posterior_g1", "posterior_g2", "posterior_g3", "posterior_g4", 
                      "posterior_phi", "posterior_sigma", "posterior_beta3", "posterior_rho")

medias <- estimacion_t_simulacion_D8_extremo_V1[,orden_parametros] %>%colMeans() 
valores_reales <- data.frame(parametro=c("posterior_g1","posterior_g2","posterior_g3","posterior_g4","posterior_phi","posterior_sigma","posterior_beta3","posterior_rho"),real=c(medias))

df_long <- df_long %>% left_join(valores_reales,by='parametro')

# Definir el orden de los parámetros en las facetas

orden_parametros <- gsub("posterior_", "", orden_parametros)
# Asegurarnos que 'cadena' esté como factor para diferenciar las dos cadenas
df_long$cadenas <- factor(df_long$cadena, levels = c(1, 2), labels = c("Primera cadena", "Segunda cadena"))

# Aseguramos que los parámetros estén en el orden correcto y quitamos "posterior"
df_long$parametro <- factor(gsub("posterior_", "", df_long$parametro), levels = orden_parametros)

df_long$parametro <- factor(df_long$parametro,labels=c("g1" = parse(text=TeX("$\\gamma_1$")), 
                                      "g2" = parse(text=TeX("$\\gamma_2$")), 
                                      "g3" = parse(text=TeX("$\\gamma_3$")), 
                                      "g4" = parse(text=TeX("$\\gamma_4$")), 
                                      "phi" = parse(text=TeX("$\\phi$")), 
                                      "sigma" = parse(text=TeX("$\\sigma$")), 
                                      "beta3" = parse(text=TeX("$\\beta_3$")), 
                                      "rho" = parse(text=TeX("$\\rho$"))  ))


# Graficamos los traceplots
p1 <- ggplot(df_long, aes(x = iteracion, y = valor, color = cadenas)) +
  geom_line(linewidth=0.5, alpha=0.6) +geom_hline(aes(yintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_y", 
             labeller = label_parsed,ncol = 4) +
  scale_color_manual(values = c("Primera cadena" = "red", "Segunda cadena" = "#377eb8"))+
   # scale_color_manual(values = c("Primera cadena" = rgb(0, 0, 0, max = 255, alpha = 128),  # Negro con transparencia
   #                             "Segunda cadena" = rgb(255, 0, 0, max = 255, alpha = 0.5))) +
  scale_x_continuous(breaks = c(0,5000,10000),labels = scales::label_number(scale = 1e-3, suffix = "k")) +  # Formato de miles
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
p1
# Graficamos los traceplots
h1 <- ggplot(df_long, aes(x = valor, fill = cadenas)) +
  geom_histogram(position = "identity", bins = 25,alpha=0.6) +geom_vline(aes(xintercept = real), color = "black", linetype = "dashed", size = 1)+ 
  facet_wrap(~parametro, scales = "free_x", 
             labeller = label_parsed,ncol = 4) +
  scale_fill_manual(values = c("Primera cadena" = "#e41a1c", "Segunda cadena" = "#377eb8"))+
  theme_bw() +
  theme(legend.position = "none",axis.text.x = element_text(size = 7),axis.text.y = element_text(size = 7)) +
  labs(x = "", y = "")
h1
```



## Error por locacion

```{r}
df_errores_locacion <- df_errores_test %>% 
  filter(error=='abs_mean',modelo %in% c('D4 M5','DY M5','D8 M4','D8 M5')) %>% 
  pivot_longer(cols=starts_with("s")) %>% 
  separate(name,c('s','id'),sep = 's')
df_errores_locacion <- cbind(rbind(locaciones_train_test,locaciones_train_test,locaciones_train_test,locaciones_train_test),df_errores_locacion)




aut_sf <- gadm(country = 'CR', level = 2, path = '.') %>% st_as_sf()
pacifico_norte_sf <- aut_sf %>% filter(NAME_1 == "Guanacaste")


grafico_errores_locacion <- ggplot(data = pacifico_norte_sf) +
  geom_sf(fill = "white", color = "black") + 
  geom_tile(data = df_errores_locacion, aes(x = lon, y = lat, fill = value), 
            width = 0.1, height = 0.1) +  # Dibujar los cuadros
  scale_fill_gradient2(
 low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", # Violeta oscuro (puede ser un color interesante para precipitación intensa)

    midpoint = mean(df_errores_locacion$value, na.rm = TRUE)  # Usar el valor medio de 'value'
  ) + 
  theme_bw() +
  labs(
    x = "Lon",
    y = "Lat",
    fill = "MQAE"  # Cambiar la etiqueta del color
  )+  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "Media"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  facet_wrap(
    ~modelo,) 
    # labeller = as_labeller(c(
    #   retorno5 = "Retorno 5 años", 
    #   retorno10 = "Retorno 10 años", 
    #   retorno15 = "Retorno 15 años", 
    #   retorno20 = "Retorno 20 años"
    # ))
    # Etiquetas personalizadas para los facetes

#theme(legend.position="bottom") 


grafico_errores_locacion

 ggsave("img_articulo/grafico_errores_locacion.pdf", plot = grafico_errores_locacion, width = 10, height = 10)
```


```{r}
grafico_errores_locacion <- ggplot(data = pacifico_norte_sf) +
  geom_sf(fill = "white", color = "black") + 
  geom_tile(data = df_errores_locacion, aes(x = lon, y = lat, fill = value), 
            width = 0.1, height = 0.1) +  # Dibujar los cuadros
  scale_fill_gradient2(
 low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", # Violeta oscuro (puede ser un color interesante para precipitación intensa)

    midpoint = mean(df_errores_locacion$value, na.rm = TRUE)  # Usar el valor medio de 'value'
  ) + 
  theme_bw() +
  labs(
    x = "Lon",
    y = "Lat",
    fill = "EACP"  # Cambiar la etiqueta del color
  )+  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "Media"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  facet_wrap(
    ~modelo,ncol = 4) 
    # labeller = as_labeller(c(
    #   retorno5 = "Retorno 5 años", 
    #   retorno10 = "Retorno 10 años", 
    #   retorno15 = "Retorno 15 años", 
    #   retorno20 = "Retorno 20 años"
    # ))
    # Etiquetas personalizadas para los facetes

#theme(legend.position="bottom") 
s

grafico_errores_locacion
 ggsave("img/grafico_errores_locacion_presentacion.pdf", plot = grafico_errores_locacion, width = 15, height = 5)
```



## QQplots


```{r}
set.seed(1)

# Leer el archivo CSV
datos_guanacaste <- read.csv('datosPrecGuanacaste.csv')
covariables_guanacaste <- read.csv('covariables_guanacaste.csv')
# Redondear latitud y longitud
datos_guanacaste$lon <- round(datos_guanacaste$lon, 3)
datos_guanacaste$lat <- round(datos_guanacaste$lat, 3)

# Ordenar por fecha
datos_guanacaste <- datos_guanacaste[order(datos_guanacaste$date), ]
datos_guanacaste <- datos_guanacaste %>% 
  filter(date>=ymd(20200901))
# Agrupar por latitud y longitud
loc <- covariables_guanacaste
loc <- loc[order(loc$lat, loc$lon, decreasing = c(T, F)), ]
loc <- loc[, c('lon', 'lat', 'alt')]

# Filtrar datos de entrenamiento
locaciones_completas <- loc[loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 10.3 & loc$lat < 10.8, ]
nsites <- nrow(locaciones_completas)



# Filtrar datos de prueba (test)
filtradora <- locaciones_completas %>% 
  mutate(lonlat = paste0(lon,lat))



# locaciones_extras_arriba <- loc[(loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 10.749 & loc$lat < 10.9), ]
# locaciones_extras_abajo <- loc[(loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 10.2 & loc$lat < 10.3), ]
# punta_abajo <- loc[(loc$lon > -85.7 & loc$lon < -85.2 & loc$lat < 9.8), ]
# punta_arriba <- loc[(loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 11.1), ]
# punta_derecha <- loc[(loc$lon > -84.9), ]
# punta_izquierda <- loc[(loc$lon < -85.8), ]
# 
# # Concatenar los datos de prueba
# locaciones_no_test <- rbind(locaciones_extras_arriba, locaciones_extras_abajo, punta_abajo, punta_arriba, punta_derecha, punta_izquierda)
# locaciones_no_test <- locaciones_no_test[order(locaciones_no_test$lat, locaciones_no_test$lon, decreasing = c(T, F)), ]%>% 
#   mutate(lonlat = paste0(lon,lat))



locaciones_test <- covariables_guanacaste %>% 
  mutate(id=1:n()) %>% 
  dplyr::filter(id %in% c(1,2,11,13,24,34,54,57,59,61,70,76,78,81,82)) %>% 
  dplyr::select(-id)




  
# Concatenar los datos de prueba
locaciones_test <- locaciones_test[order(locaciones_test$lat, locaciones_test$lon, decreasing = c(T, F)), ]

# Concatenar datos de entrenamiento y prueba
locaciones_train_test <- covariables_guanacaste
locaciones_train_test <- locaciones_train_test[order(locaciones_train_test$lat, locaciones_train_test$lon, decreasing = c(T, F)), ]

# Renombrar columnas
locaciones_train_test$lat_x <- locaciones_train_test$lat
locaciones_train_test$lon_x <- locaciones_train_test$lon
locaciones_train_test <- locaciones_train_test %>% dplyr::select(-lat,-lon)



# Hacer merge con locaciones_test
locaciones_train_test <- locaciones_train_test  %>% mutate(lonlat=paste0(lat_x,lon_x))%>% left_join( locaciones_test %>% mutate(lonlat=paste0(lat,lon)), "lonlat")

# Agregar la columna 'tipo' para indicar si es 'train' o 'test'
locaciones_train_test$tipo <- ifelse(is.na(locaciones_train_test$lon), 'train', 'test')

# Seleccionar columnas relevantes
locaciones_train_test <- locaciones_train_test[, c('lon_x', 'lat_x','alt.x', 'tipo')]

# Renombrar columnas
colnames(locaciones_train_test)[1:3] <- c('lon', 'lat','alt')



locaciones_test_completa <- covariables_guanacaste %>% 
  mutate(id=1:n()) %>% 
  dplyr::filter(!(paste0(lon,lat) %in% filtradora$lonlat )) %>% 
  mutate(Tipo='Test',Tipo2=ifelse(id %in% c(1,2,11,13,24,34,54,57,59,61,70,76,78,81,82),'Test','Test_grande')) %>% 
  dplyr::select(-X,-id)


# Ensure aut is in sf format
aut_sf <- gadm(country = 'CR', level = 2, path = '.') %>% st_as_sf()

# Extract the specific region for PacificoNorte
pacifico_norte_sf <- aut_sf %>% filter(NAME_1 == "Guanacaste")



locaciones_para_grafico_train_test <- rbind(
  locaciones_completas %>% mutate(Tipo = 'Train',Tipo2='Train'),
  locaciones_test_completa
) %>%
  mutate(Tipo = factor(Tipo, levels = c("Train", "Test")))  # <- Orden deseado

p_altitud <- ggplot(data = pacifico_norte_sf) +
    geom_sf(fill = "white", color = "black")+ 
  geom_point(data = locaciones_para_grafico_train_test, aes(x = lon, y = lat, color = alt,shape=Tipo2), size = 5) +  # Dibujar los puntos
  facet_wrap(~Tipo)+
  scale_color_gradient2( low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", midpoint = mean(locaciones_para_grafico_train_test$alt))+theme_bw()+
   scale_shape_manual(values = c("Train" = 16, "Test_grande" = 16, "Test" = 17))+
   guides(shape = "none") +
  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "Altitude"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) 


 ggsave("img_articulo/grafico_train_test_altitud.pdf", plot = p_altitud, width = 10, height = 5)

# Obtener el número de sitios en el conjunto de datos final
nsites_train_test <- nrow(locaciones_train_test)


# Definir las covariables espaciales
Z1 <- locaciones_completas$lon  # primera covariable espacial
Z2 <- locaciones_completas$lat  # segunda covariable espacial
Z12 <- locaciones_completas$lon^2  # primera covariable espacial al cuadrado
Z22 <- locaciones_completas$lat^2  # segunda covariable espacial al cuadrado
Z3 <- locaciones_completas$alt  # tercera covariable (altitud)
Z32 <- locaciones_completas$alt^2  # altitud al cuadrado

# Definir las covariables espaciales para el conjunto de entrenamiento y prueba
Z1_train_test <- locaciones_train_test$lon  # primera covariable espacial
Z2_train_test <- locaciones_train_test$lat  # segunda covariable espacial
Z12_train_test <- locaciones_train_test$lon^2  # primera covariable espacial al cuadrado
Z22_train_test <- locaciones_train_test$lat^2  # segunda covariable espacial al cuadrado
Z3_train_test <- locaciones_train_test$alt  # tercera covariable (altitud)
Z32_train_test <- locaciones_train_test$alt^2  # altitud al cuadrado

# Función para normalización Min-Max
normalize_min_max <- function(x,minz,maxz) {
  return((x -minz) / (maxz- minz))
}

# Normalizar las covariables
a <- min(Z1)
b <- max(Z1)
Z1 <- normalize_min_max(Z1,a,b)
Z1_train_test <- normalize_min_max(Z1_train_test,a,b)
a <- min(Z2)
b <- max(Z2)
Z2 <- normalize_min_max(Z2,a,b)
Z2_train_test <- normalize_min_max(Z2_train_test,a,b)

a <- min(Z12)
b <- max(Z12)

Z12 <- normalize_min_max(Z12,a,b)
Z12_train_test <- normalize_min_max(Z12_train_test,a,b)

a <- min(Z22)
b <- max(Z22)


Z22 <- normalize_min_max(Z22,a,b)
Z22_train_test <- normalize_min_max(Z22_train_test,a,b)

a <- min(Z3)
b <- max(Z3)

Z3 <- normalize_min_max(Z3,a,b)
Z3_train_test <- normalize_min_max(Z3_train_test,a,b)

a <- min(Z32)
b <- max(Z32)

Z32 <- normalize_min_max(Z32,a,b)
Z32_train_test <- normalize_min_max(Z32_train_test,a,b)

# Calcular la matriz de distancia entre los sitios
dist_mat <- as.matrix(dist(locaciones_completas[, c("lon", "lat")]))  # matriz de distancia (nsites x nsites)
dist_mat_train_test <- as.matrix(dist(locaciones_train_test[, c("lon", "lat")]))  # matriz de distancia para train test

# Mostrar el rango de la distancia para verificar el valor máximo
rho_upper_range <- 2 * max(dist_mat)

# Crear la matriz de covariables para el conjunto de datos de entrenamiento
cov_original <- cbind(1, Z1, Z2, Z3, Z12, Z22, Z32)  # matriz de diseño (nsites x 7)

# Crear la matriz de covariables para el conjunto de datos de entrenamiento y prueba
cov_original_train_test <- cbind(1, Z1_train_test, Z2_train_test, Z3_train_test, Z12_train_test, Z22_train_test, Z32_train_test)  # matriz de diseño (nsites x 7)

# Calcular el valor de m
m <- nrow(datos_guanacaste) / nrow(loc)

# Mostrar información de las localizaciones
cat(nsites, "locaciones\n")
cat(m, "en tiempo\n")

cat(nsites_train_test, "locaciones en train test\n")
cat(m, "en tiempo\n")

# Filtrar los datos para entrenamiento y prueba
datos_guanacaste_filtrados <- merge(datos_guanacaste, locaciones_completas, by = c("lon", "lat"))
datos_guanacaste_filtrados_train_test <- merge(datos_guanacaste, locaciones_train_test, by = c("lon", "lat"))

#########################################################################
# Inicializar la matriz de covariables para el conjunto de entrenamiento
X_train_guanacaste <- matrix(0, nrow = m, ncol = nsites)

for (sitio in 1:nsites) {
  lon_actual <- locaciones_completas$lon[sitio]
  lat_actual <- locaciones_completas$lat[sitio]
  
  # Filtrar los datos para el sitio actual
  auxi <- datos_guanacaste_filtrados[datos_guanacaste_filtrados$lon == lon_actual & datos_guanacaste_filtrados$lat == lat_actual, ]
  auxi <- auxi[order(auxi$date), ]$chirps  # Ordenar por fecha y extraer los valores de 'chirps'
  
  # Calcular el cuantil 75
  cuantil_75 <- quantile(auxi, 0.75)
  
  # Asignar el valor a la matriz X_train_guanacaste
  X_train_guanacaste[,sitio] <- ifelse(auxi < cuantil_75, cuantil_75, auxi)
}



########################################################################


# Inicializar la matriz de covariables para el conjunto de entrenamiento y prueba
X_train_guanacaste_train_test <- matrix(0, nrow = m, ncol = nsites_train_test)

for (sitio in 1:nsites_train_test) {
  lon_actual <- locaciones_train_test$lon[sitio]
  lat_actual <- locaciones_train_test$lat[sitio]
  
  # Filtrar los datos para el sitio actual
  auxi <- datos_guanacaste_filtrados_train_test[datos_guanacaste_filtrados_train_test$lon == lon_actual & datos_guanacaste_filtrados_train_test$lat == lat_actual, ]
  auxi <- auxi[order(auxi$date), ]$chirps  # Ordenar por fecha y extraer los valores de 'chirps'
  
  # Calcular el cuantil 75
  cuantil_75 <- quantile(auxi, 0.75)
  
  # Asignar el valor a la matriz X_train_guanacaste_train_test
  X_train_guanacaste_train_test[,sitio] <- ifelse(auxi < cuantil_75, cuantil_75, auxi)
}
```



```{r}
# D4 M5

#params_covariables <- c(1.488737205	,0.750409757,	-0.118023769,	0.258848217	,0.749365158)
#params_parametros <- c(0.297792188,	0.145533655,	2.243615325,	1.090473965)

# D8 M5

params_covariables <- c(1.504204516	,0.683223936,	-0.153615449,	0.24715368,	0.662004287
)
params_parametros <- c(-0.062703381	,0.258503745,	2.581739028	,1.087263909)

# D7 M3

params_covariables <- c(2.207068642,	0.048585554	,-0.003408484)
params_parametros <- c(0.820969353	,0.417626287,	2.829402108,0.426987008)

# DY M5
params_covariables <- c(1.254907066,	0.900904111	,-0.175850387	,0.278619086,	0.911298429
)
params_parametros <- c(0.91814632,	0.100208261,	3.909503819	,0.346104934
)
```


```{r}
params_covariables <- c(1.54	,0.76,	-0.13,	0.25	,0.80)
params_parametros <- c(0.60,	0.13,	2.08,	1.66)

```


```{r}
lista_cuantiles_simulados_sitio <- vector("list", nsites_train_test)
nprocesos <- 100

for(i in 1:nsites_train_test) {
  lista_cuantiles_simulados_sitio[[i]] <- matrix(nrow=nprocesos,ncol = 100)
}

for (z in 1:nprocesos) {
  simul <- proceso_estimacion(params_covariables, params_parametros, nsites_train_test, m, cov_original_train_test[,1:length(params_covariables)], dist_mat_train_test,'D4')
  for (j in 1:nsites_train_test) {
      lista_cuantiles_simulados_sitio[[j]][z,] <- sapply(0:99, function(k) quantile(simul[,j], k / 100))
  }

}

```

```{r}
muestras_test <- which(locaciones_train_test$tipo=='test')

locaciones_train_test
plots_cuantiles <- lapply(muestras_test, 
  function(lugar){
  cuantil_ic_superior <- as.vector(sapply(1:100, function(k) quantile(lista_cuantiles_simulados_sitio[[lugar]][,k], 0.975)))
  cuantil_media <- sapply(1:100, function(k) mean(lista_cuantiles_simulados_sitio[[lugar]][,k]))
  cuantil_ic_inferior <- as.vector(sapply(1:100, function(k) quantile(lista_cuantiles_simulados_sitio[[lugar]][,k], 0.025)))
  
  # Obtener las coordenadas y el tipo de ubicación actual
  lon_actual <- locaciones_train_test$lon[lugar]
  lat_actual <- locaciones_train_test$lat[lugar]
  tipo_actual <- locaciones_train_test$tipo[lugar]

  # Obtener las mediciones reales de datos_guanacaste_df
  measurements1 <- datos_guanacaste_filtrados_train_test %>%
    dplyr::filter(lon == lon_actual & lat == lat_actual) %>%
    dplyr::arrange(date) %>%
    dplyr::pull(chirps)
  
  # Calcular el cuantil 75 y ajustarlo en measurements1
  cuantil_75 <- quantile(measurements1, 0.75)
  measurements1 <- pmax(measurements1, cuantil_75)
  
  # Calcular los cuantiles para real y simulado
  q_real <- sapply(0:99, function(k) quantile(measurements1, k / 100))
  
  
  p <- ggplot() +
    geom_point(aes(x = q_real, y = cuantil_media)) +
    geom_abline(slope = 1, intercept = 0, linetype = "dashed", color = "red") +
    geom_ribbon(aes(x = q_real, ymin = cuantil_ic_inferior, ymax = cuantil_ic_superior), alpha = 0.2, fill = "blue") +  # Intervalo de confianza simulado
    labs(
      #title = paste(tipo_actual, ", ", lon_actual, " (-) ", lat_actual, " : ", lugar),
      title = paste("Site ", lugar),
      x = "Empirical quantiles",
      y = "Fitted quantiles"
    ) +
    theme_bw()+theme_update(plot.title = element_text(hjust = 0.5))
  p

  
  
  }
)
graficos_qqplot_test <- gridExtra::grid.arrange(grobs=plots_cuantiles,ncol=5)
ggsave("img_articulo/grafico_qqplot_test_D4_M5.pdf", plot = graficos_qqplot_test, width = 10, height = 10)

```

```{r}
graficos_qqplot_test <- gridExtra::grid.arrange(grobs=plots_cuantiles,nrow=2)
ggsave("img/grafico_qqplot_test_D4_M5_presentacion.pdf", plot = graficos_qqplot_test, width = 20, height = 10)
```


## Períodos de retorno


https://cran.r-project.org/web/packages/extremeStat/vignettes/extremeStat.html

```{r}
set.seed(1)

# Leer el archivo CSV
datos_guanacaste <- read.csv('datosPrecGuanacaste.csv')
covariables_guanacaste <- read.csv('covariables_guanacaste.csv')
# Redondear latitud y longitud
datos_guanacaste$lon <- round(datos_guanacaste$lon, 3)
datos_guanacaste$lat <- round(datos_guanacaste$lat, 3)

# Ordenar por fecha
datos_guanacaste <- datos_guanacaste[order(datos_guanacaste$date), ]

# Agrupar por latitud y longitud
loc <- covariables_guanacaste
loc <- loc[order(loc$lat, loc$lon, decreasing = c(T, F)), ]
loc <- loc[, c('lon', 'lat', 'alt')]

# Filtrar datos de entrenamiento
locaciones_completas <- loc[loc$lon > -85.7 & loc$lon < -85.2 & loc$lat > 10.3 & loc$lat < 10.8, ]
nsites <- nrow(locaciones_completas)



# Filtrar datos de prueba (test)
filtradora <- locaciones_completas %>% 
  mutate(lonlat = paste0(lon,lat))

locaciones_test <- covariables_guanacaste %>% 
  filter(!(paste0(lon,lat) %in% filtradora$lonlat))
  
  
# Concatenar los datos de prueba
locaciones_test <- locaciones_test[order(locaciones_test$lat, locaciones_test$lon, decreasing = c(T, F)), ]

# Concatenar datos de entrenamiento y prueba
locaciones_train_test <- covariables_guanacaste
locaciones_train_test <- locaciones_train_test[order(locaciones_train_test$lat, locaciones_train_test$lon, decreasing = c(T, F)), ]

# Renombrar columnas
locaciones_train_test$lat_x <- locaciones_train_test$lat
locaciones_train_test$lon_x <- locaciones_train_test$lon
locaciones_train_test <- locaciones_train_test %>% dplyr::select(-lat,-lon)



# Hacer merge con locaciones_test
locaciones_train_test <- locaciones_train_test  %>% mutate(lonlat=paste0(lat_x,lon_x))%>% left_join( locaciones_test %>% mutate(lonlat=paste0(lat,lon)), "lonlat")

# Agregar la columna 'tipo' para indicar si es 'train' o 'test'
locaciones_train_test$tipo <- ifelse(is.na(locaciones_train_test$lon), 'train', 'test')

# Seleccionar columnas relevantes
locaciones_train_test <- locaciones_train_test[, c('lon_x', 'lat_x','alt.x', 'tipo')]

# Renombrar columnas
colnames(locaciones_train_test)[1:3] <- c('lon', 'lat','alt')

# Obtener el número de sitios en el conjunto de datos final
nsites_train_test <- nrow(locaciones_train_test)


# Definir las covariables espaciales
Z1 <- locaciones_completas$lon  # primera covariable espacial
Z2 <- locaciones_completas$lat  # segunda covariable espacial
Z12 <- locaciones_completas$lon^2  # primera covariable espacial al cuadrado
Z22 <- locaciones_completas$lat^2  # segunda covariable espacial al cuadrado
Z3 <- locaciones_completas$alt  # tercera covariable (altitud)
Z32 <- locaciones_completas$alt^2  # altitud al cuadrado

# Definir las covariables espaciales para el conjunto de entrenamiento y prueba
Z1_train_test <- locaciones_train_test$lon  # primera covariable espacial
Z2_train_test <- locaciones_train_test$lat  # segunda covariable espacial
Z12_train_test <- locaciones_train_test$lon^2  # primera covariable espacial al cuadrado
Z22_train_test <- locaciones_train_test$lat^2  # segunda covariable espacial al cuadrado
Z3_train_test <- locaciones_train_test$alt  # tercera covariable (altitud)
Z32_train_test <- locaciones_train_test$alt^2  # altitud al cuadrado

# Función para normalización Min-Max
normalize_min_max <- function(x) {
  return((x - min(x)) / (max(x) - min(x)))
}

# Normalizar las covariables
Z1 <- normalize_min_max(Z1)
Z1_train_test <- normalize_min_max(Z1_train_test)

Z2 <- normalize_min_max(Z2)
Z2_train_test <- normalize_min_max(Z2_train_test)

Z12 <- normalize_min_max(Z12)
Z12_train_test <- normalize_min_max(Z12_train_test)

Z22 <- normalize_min_max(Z22)
Z22_train_test <- normalize_min_max(Z22_train_test)

Z3 <- normalize_min_max(Z3)
Z3_train_test <- normalize_min_max(Z3_train_test)

Z32 <- normalize_min_max(Z32)
Z32_train_test <- normalize_min_max(Z32_train_test)

# Calcular la matriz de distancia entre los sitios
dist_mat <- as.matrix(dist(locaciones_completas[, c("lon", "lat")]))  # matriz de distancia (nsites x nsites)
dist_mat_train_test <- as.matrix(dist(locaciones_train_test[, c("lon", "lat")]))  # matriz de distancia para train test

# Mostrar el rango de la distancia para verificar el valor máximo
rho_upper_range <- 2 * max(dist_mat)

# Crear la matriz de covariables para el conjunto de datos de entrenamiento
cov_original <- cbind(1, Z1, Z2, Z3, Z12, Z22, Z32)  # matriz de diseño (nsites x 7)

# Crear la matriz de covariables para el conjunto de datos de entrenamiento y prueba
cov_original_train_test <- cbind(1, Z1_train_test, Z2_train_test, Z3_train_test, Z12_train_test, Z22_train_test, Z32_train_test)  # matriz de diseño (nsites x 7)

# Calcular el valor de m
m <- nrow(datos_guanacaste) / nrow(loc)

# Mostrar información de las localizaciones
cat(nsites, "locaciones\n")
cat(m, "en tiempo\n")

cat(nsites_train_test, "locaciones en train test\n")
cat(m, "en tiempo\n")

# Filtrar los datos para entrenamiento y prueba
datos_guanacaste_filtrados <- merge(datos_guanacaste, locaciones_completas, by = c("lon", "lat"))
datos_guanacaste_filtrados_train_test <- merge(datos_guanacaste, locaciones_train_test, by = c("lon", "lat"))

#########################################################################
# Inicializar la matriz de covariables para el conjunto de entrenamiento
X_train_guanacaste <- matrix(0, nrow = m, ncol = nsites)

for (sitio in 1:nsites) {
  lon_actual <- locaciones_completas$lon[sitio]
  lat_actual <- locaciones_completas$lat[sitio]
  
  # Filtrar los datos para el sitio actual
  auxi <- datos_guanacaste_filtrados[datos_guanacaste_filtrados$lon == lon_actual & datos_guanacaste_filtrados$lat == lat_actual, ]
  auxi <- auxi[order(auxi$date), ]$chirps  # Ordenar por fecha y extraer los valores de 'chirps'
  
  # Calcular el cuantil 75
  cuantil_75 <- quantile(auxi, 0.75)
  
  # Asignar el valor a la matriz X_train_guanacaste
  X_train_guanacaste[,sitio] <- ifelse(auxi < cuantil_75, cuantil_75, auxi)
}



########################################################################


# Inicializar la matriz de covariables para el conjunto de entrenamiento y prueba
X_train_guanacaste_train_test <- matrix(0, nrow = m, ncol = nsites_train_test)

for (sitio in 1:nsites_train_test) {
  lon_actual <- locaciones_train_test$lon[sitio]
  lat_actual <- locaciones_train_test$lat[sitio]
  
  # Filtrar los datos para el sitio actual
  auxi <- datos_guanacaste_filtrados_train_test[datos_guanacaste_filtrados_train_test$lon == lon_actual & datos_guanacaste_filtrados_train_test$lat == lat_actual, ]
  auxi <- auxi[order(auxi$date), ]$chirps  # Ordenar por fecha y extraer los valores de 'chirps'
  
  # Calcular el cuantil 75
  cuantil_75 <- quantile(auxi, 0.75)
  
  # Asignar el valor a la matriz X_train_guanacaste_train_test
  X_train_guanacaste_train_test[,sitio] <- ifelse(auxi < cuantil_75, cuantil_75, auxi)
}



```

```{r}

params_covariables <- c(1.54	,0.76,	-0.13,	0.25	,0.80)
params_parametros <- c(0.60,	0.13,	2.08,	1.66)


lista_retornos_simulados_sitio <- vector("list", nsites_train_test)
nprocesos <- 1

for(i in 1:nsites_train_test) {
  lista_retornos_simulados_sitio[[i]] <- matrix(nrow=nprocesos,ncol = 4)
}

for (z in 1:nprocesos) {
  simul <- proceso_estimacion(params_covariables, params_parametros, nsites_train_test, 1000000, cov_original_train_test[,1:5], dist_mat_train_test,'D4')
  
  for (j in 1:nsites_train_test) {
    anio1<- 1-1/(1*153)
    anio5<- 1-1/(5*153)
    anio10<- 1-1/(10*153)
    anio15<- 1-1/(15*153)
    anio20<- 1-1/(20*153)
    lista_retornos_simulados_sitio[[j]][z,] <- sapply(c(anio5,anio10,anio15,anio20), function(k) quantile(simul[,j], k ))
  }

}

plot(simul[,1])

```

```{r}
max(X_train_guanacaste_train_test[,1])

quantile(simul[,1], anio5 )
```

```{r}
df_retornos_locacion <- data.frame()
for (lugar in 1:nsites_train_test) {
  lon_actual <- locaciones_train_test$lon[lugar]
  lat_actual <- locaciones_train_test$lat[lugar]
  retornos_locacion <- lista_retornos_simulados_sitio[[lugar]] %>% colMeans()
  df_retornos_locacion <- rbind(df_retornos_locacion,data.frame(lon=lon_actual,lat=lat_actual,retorno5=retornos_locacion[1],retorno10=retornos_locacion[2],retorno15=retornos_locacion[3],retorno20=retornos_locacion[4]))
  
  
}

df_retornos_locacion_pivot <- df_retornos_locacion %>% 
  pivot_longer(cols = c('retorno5','retorno10','retorno15','retorno20')) %>%
  mutate(name = factor(name, levels = c('retorno5', 'retorno10', 'retorno15', 'retorno20')))

# Crear el gráfico ajustado
grafico_retornos <- ggplot(data = pacifico_norte_sf) +
  geom_sf(fill = "white", color = "black") + 
  geom_tile(data = df_retornos_locacion_pivot, aes(x = lon, y = lat, fill = value), 
            width = 0.1, height = 0.1) +  # Dibujar los cuadros
  scale_fill_gradient2(
 low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", # Violeta oscuro (puede ser un color interesante para precipitación intensa)

    midpoint = mean(df_retornos_locacion_pivot$value, na.rm = TRUE)  # Usar el valor medio de 'value'
  ) + 
  theme_bw() +
  labs(
    x = "Lon",
    y = "Lat",
    fill = "Precipitation"  # Cambiar la etiqueta del color
  )+  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "Media"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  facet_wrap(
    ~name, 
    labeller = as_labeller(c(
      retorno5 = "5 years return level", 
      retorno10 = "10 years return level", 
      retorno15 = "15 years return level", 
      retorno20 = "20 years return level"
    ))
  )  # Etiquetas personalizadas para los facetes

 ggsave("img_articulo/grafico_retornos.pdf", plot = grafico_retornos, width = 10, height = 10)
```


```{r}
df_retornos_locacion <- data.frame()
for (lugar in 1:nsites_train_test) {
  lon_actual <- locaciones_train_test$lon[lugar]
  lat_actual <- locaciones_train_test$lat[lugar]
  retornos_locacion <- lista_retornos_simulados_sitio[[lugar]] %>% colMeans()
  df_retornos_locacion <- rbind(df_retornos_locacion,data.frame(lon=lon_actual,lat=lat_actual,retorno5=retornos_locacion[1],retorno10=retornos_locacion[2],retorno15=retornos_locacion[3],retorno20=retornos_locacion[4]))
  
  
}

df_retornos_locacion_pivot <- df_retornos_locacion %>% 
  pivot_longer(cols = c('retorno5','retorno10','retorno15','retorno20')) %>%
  mutate(name = factor(name, levels = c('retorno5', 'retorno10', 'retorno15', 'retorno20')))

# Crear el gráfico ajustado
grafico_retornos <- ggplot(data = pacifico_norte_sf) +
  geom_sf(fill = "white", color = "black") + 
  geom_tile(data = df_retornos_locacion_pivot, aes(x = lon, y = lat, fill = value), 
            width = 0.1, height = 0.1) +  # Dibujar los cuadros
  scale_fill_gradient2(
 low = "#b3cde0",  # Azul claro
  mid = "#ffecb3",  # Amarillo pálido
  high = "#6a3d9a", # Violeta oscuro (puede ser un color interesante para precipitación intensa)

    midpoint = mean(df_retornos_locacion_pivot$value, na.rm = TRUE)  # Usar el valor medio de 'value'
  ) + 
  theme_bw() +
  labs(
    x = "Lon",
    y = "Lat",
    fill = "Precipitación"  # Cambiar la etiqueta del color
  )+  labs(
    #title = "Locaciones con su media representada por color",
    x = "Lon (°W)",
    y = "Lat (°N)",
    color = "Media"
  ) +  scale_x_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  scale_y_continuous(
    labels = function(x) sprintf("%.1f", x)
  ) +
  facet_wrap(
    ~name, 
    labeller = as_labeller(c(
      retorno5 = "Retorno 5 años", 
      retorno10 = "Retorno 10 años", 
      retorno15 = "Retorno 15 años", 
      retorno20 = "Retorno 20 años"
    )),ncol = 4
  )  # Etiquetas personalizadas para los facetes

 ggsave("img/grafico_retornos_presentacion.pdf", plot = grafico_retornos, width = 15, height = 5)
```


```{r}
# p5 <- ggplot(data = pacifico_norte_sf) +
#   geom_sf() + 
#   geom_tile(data = df_retornos_locacion, aes(x = lon, y = lat, fill = retorno5), width = 0.1, height = 0.1) +  # Dibujar los cuadros
#   scale_fill_gradient2(low = "blue", mid = "#e9e29c", high = "red", midpoint = mean(df_retornos_locacion$retorno5)) + 
#   theme_bw() +
#   labs(
#     x = "Lon",
#     y = "Lat",
#     fill = "retorno5"
#   )+
#   guides(fill = guide_colorbar(title = "Nivel \n de \n retorno \n5 años", title.position = "top", title.hjust = 0.5))
# 
# 
# 
# p10 <- ggplot(data = pacifico_norte_sf) +
#   geom_sf() + 
#   geom_tile(data = df_retornos_locacion, aes(x = lon, y = lat, fill = retorno10), width = 0.1, height = 0.1) +  # Dibujar los cuadros
#   scale_fill_gradient2(low = "blue", mid = "#e9e29c", high = "red", midpoint = mean(df_retornos_locacion$retorno10)) + 
#   theme_bw() +
#   labs(
#     x = "Lon",
#     y = "Lat",
#     fill = "retorno10"
#   )+
#   guides(fill = guide_colorbar(title = "Nivel \n de \n retorno \n10 años", title.position = "top", title.hjust = 0.5))
# 
# 
# 
# 
# p15 <- ggplot(data = pacifico_norte_sf) +
#   geom_sf() + 
#   geom_tile(data = df_retornos_locacion, aes(x = lon, y = lat, fill = retorno15), width = 0.1, height = 0.1) +  # Dibujar los cuadros
#   scale_fill_gradient2(low = "blue", mid = "#e9e29c", high = "red", midpoint = mean(df_retornos_locacion$retorno15)) + 
#   theme_bw() +
#   labs(
#     x = "Lon",
#     y = "Lat",
#     fill = "retorno15"
#   )+
#   guides(fill = guide_colorbar(title = "Nivel \n de \n retorno \n15 años", title.position = "top", title.hjust = 0.5))
# 
# 
# 
# p20 <- ggplot(data = pacifico_norte_sf) +
#   geom_sf() + 
#   geom_tile(data = df_retornos_locacion, aes(x = lon, y = lat, fill = retorno20), width = 0.1, height = 0.1) +  # Dibujar los cuadros
#   scale_fill_gradient2(low = "blue", mid = "#e9e29c", high = "red", midpoint = mean(df_retornos_locacion$retorno20)) + 
#   theme_bw() +
#   labs(
#     x = "Lon",
#     y = "Lat",
#     fill = "retorno20"
#   )+
#   guides(fill = guide_colorbar(title = "Nivel \n de \n retorno \n20 años", title.position = "top", title.hjust = 0.5))
# 
# ggsave("grafico_retornos.pdf", plot = grid.arrange(p5,p10,p15,p20,ncol=2,nrow=2), width = 10, height = 10)

```






